CMaNGOS_WoTLK: UpdateFields.cpp File Reference
UpdateFields.cpp File Reference
#include "UpdateFields.h"
#include "Log.h"
#include "ObjectGuid.h"
#include <array>
#include <vector>
Functions
template<std::size_t SIZE>
static std::array< uint16, SIZE > SetupUpdateFieldFlagsArray (uint8 objectTypeMask)
Variables
static std::array< UpdateFieldData, 381 > const g_updateFieldsData
static std::array< uint16, CONTAINER_END > const g_containerUpdateFieldFlags = SetupUpdateFieldFlagsArray<CONTAINER_END>(TYPEMASK_OBJECT | TYPEMASK_ITEM | TYPEMASK_CONTAINER)
static std::array< uint16, PLAYER_END > const g_playerUpdateFieldFlags = SetupUpdateFieldFlagsArray<PLAYER_END>(TYPEMASK_OBJECT | TYPEMASK_UNIT | TYPEMASK_PLAYER)
static std::array< uint16, GAMEOBJECT_END > const g_gameObjectUpdateFieldFlags = SetupUpdateFieldFlagsArray<GAMEOBJECT_END>(TYPEMASK_OBJECT | TYPEMASK_GAMEOBJECT)
static std::array< uint16, DYNAMICOBJECT_END > const g_dynamicObjectUpdateFieldFlags = SetupUpdateFieldFlagsArray<DYNAMICOBJECT_END>(TYPEMASK_OBJECT | TYPEMASK_DYNAMICOBJECT)
static std::array< uint16, CORPSE_END > const g_corpseUpdateFieldFlags = SetupUpdateFieldFlagsArray<CORPSE_END>(TYPEMASK_OBJECT | TYPEMASK_CORPSE)
Function Documentation
SetupUpdateFieldFlagsArray()
template<std::size_t SIZE> static std::array<uint16, SIZE> SetupUpdateFieldFlagsArray (uint8 objectTypeMask) static
Definition at line 423 of file UpdateFields.cpp.
References g_updateFieldsData.
Variable Documentation
g_containerUpdateFieldFlags
std::array<uint16, CONTAINER_END> const g_containerUpdateFieldFlags = SetupUpdateFieldFlagsArray<CONTAINER_END>(TYPEMASK_OBJECT | TYPEMASK_ITEM | TYPEMASK_CONTAINER) static
Definition at line 439 of file UpdateFields.cpp.
Referenced by UpdateFields::GetUpdateFieldFlagsArray().
g_corpseUpdateFieldFlags
std::array<uint16, CORPSE_END> const g_corpseUpdateFieldFlags = SetupUpdateFieldFlagsArray<CORPSE_END>(TYPEMASK_OBJECT | TYPEMASK_CORPSE) static
Definition at line 443 of file UpdateFields.cpp.
Referenced by UpdateFields::GetUpdateFieldFlagsArray().
g_dynamicObjectUpdateFieldFlags
std::array<uint16, DYNAMICOBJECT_END> const g_dynamicObjectUpdateFieldFlags = SetupUpdateFieldFlagsArray<DYNAMICOBJECT_END>(TYPEMASK_OBJECT | TYPEMASK_DYNAMICOBJECT) static
Definition at line 442 of file UpdateFields.cpp.
Referenced by UpdateFields::GetUpdateFieldFlagsArray().
g_gameObjectUpdateFieldFlags
std::array<uint16, GAMEOBJECT_END> const g_gameObjectUpdateFieldFlags = SetupUpdateFieldFlagsArray<GAMEOBJECT_END>(TYPEMASK_OBJECT | TYPEMASK_GAMEOBJECT) static
Definition at line 441 of file UpdateFields.cpp.
Referenced by UpdateFields::GetUpdateFieldFlagsArray().
g_playerUpdateFieldFlags
std::array<uint16, PLAYER_END> const g_playerUpdateFieldFlags = SetupUpdateFieldFlagsArray<PLAYER_END>(TYPEMASK_OBJECT | TYPEMASK_UNIT | TYPEMASK_PLAYER) static
Definition at line 440 of file UpdateFields.cpp.
Referenced by UpdateFields::GetUpdateFieldFlagsArray().
g_updateFieldsData
std::array<UpdateFieldData, 381> const g_updateFieldsData static
Definition at line 29 of file UpdateFields.cpp.
Referenced by UpdateFields::GetUpdateFieldDataByName(), UpdateFields::GetUpdateFieldDataByTypeMaskAndOffset(), and SetupUpdateFieldFlagsArray().