CMaNGOS_WoTLK: utgarde_keep.cpp File Reference
utgarde_keep.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "utgarde_keep.h"
Enumerations
enum {
SAY_SKA_DEATH = -1574012 , SAY_SKA_DEATH_REAL = -1574013 , SAY_DAL_DEATH = -1574017 , SAY_DAL_DEATH_REAL = -1574018 ,
SPELL_SUMMON_DAL_GHOST = 48612 , SPELL_SUMMON_SKA_GHOST = 48613
}
Functions
InstanceData * GetInstanceData_instance_utgarde_keep (Map *pMap)
void AddSC_instance_utgarde_keep ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_SKA_DEATH
SAY_SKA_DEATH_REAL
SAY_DAL_DEATH
SAY_DAL_DEATH_REAL
SPELL_SUMMON_DAL_GHOST
SPELL_SUMMON_SKA_GHOST
Definition at line 27 of file utgarde_keep.cpp.
Function Documentation
AddSC_instance_utgarde_keep()
void AddSC_instance_utgarde_keep ()
Definition at line 270 of file utgarde_keep.cpp.
References Script::GetInstanceData, GetInstanceData_instance_utgarde_keep(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetInstanceData_instance_utgarde_keep()
InstanceData* GetInstanceData_instance_utgarde_keep (Map * pMap)
Definition at line 265 of file utgarde_keep.cpp.
Referenced by AddSC_instance_utgarde_keep().