CMaNGOS_WoTLK: utgarde_pinnacle.cpp File Reference
utgarde_pinnacle.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "utgarde_pinnacle.h"
Enumerations
enum {
SAY_INTRO_1 = -1575000 , SAY_INTRO_2_ARTHAS = -1575001 , SAY_INTRO_3 = -1575002 , SAY_INTRO_4_ARTHAS = -1575003 ,
SAY_INTRO_5 = -1575004 , SPELL_TRANSFORMING = 54205 , SPELL_TRANSFORMING_FLOATING = 54140 , SPELL_TRANSFORMING_CHANNEL = 54142
}
Functions
InstanceData * GetInstanceData_instance_pinnacle (Map *pMap)
bool AreaTrigger_at_svala_intro (Player *pPlayer, AreaTriggerEntry const *)
void AddSC_instance_pinnacle ()
Variables
static const DialogueEntry aPinnacleDialogue []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_INTRO_1
SAY_INTRO_2_ARTHAS
SAY_INTRO_3
SAY_INTRO_4_ARTHAS
SAY_INTRO_5
SPELL_TRANSFORMING
SPELL_TRANSFORMING_FLOATING
SPELL_TRANSFORMING_CHANNEL
Definition at line 27 of file utgarde_pinnacle.cpp.
Function Documentation
AddSC_instance_pinnacle()
void AddSC_instance_pinnacle ()
Definition at line 549 of file utgarde_pinnacle.cpp.
References AreaTrigger_at_svala_intro(), Script::GetInstanceData, GetInstanceData_instance_pinnacle(), Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_svala_intro()
bool AreaTrigger_at_svala_intro (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 535 of file utgarde_pinnacle.cpp.
References WorldObject::GetInstanceData(), Player::IsGameMaster(), NOT_STARTED, SPECIAL, and TYPE_SVALA.
Referenced by AddSC_instance_pinnacle().
GetInstanceData_instance_pinnacle()
InstanceData* GetInstanceData_instance_pinnacle (Map * pMap)
Definition at line 530 of file utgarde_pinnacle.cpp.
Referenced by AddSC_instance_pinnacle().
Variable Documentation
aPinnacleDialogue
const DialogueEntry aPinnacleDialogue[] static
Initial value:
=
{
    {NPC_ARTHAS_IMAGE,              0,                      1000},
    {SAY_INTRO_1,                   NPC_SVALA,              9000},
    {SAY_INTRO_2_ARTHAS,            NPC_ARTHAS_IMAGE,       10000},
    {SPELL_TRANSFORMING_CHANNEL,    0,                      1000},
    {NPC_SVALA,                     0,                      6000},
    {SPELL_TRANSFORMING_FLOATING,   0,                      4000},
    {SPELL_TRANSFORMING,            0,                      2000},
    {SAY_INTRO_3,                   NPC_SVALA_SORROWGRAVE,  11000},
    {SAY_INTRO_4_ARTHAS,            NPC_ARTHAS_IMAGE,       10000},
    {SAY_INTRO_5,                   NPC_SVALA_SORROWGRAVE,  13000},
    {NPC_SVALA_SORROWGRAVE,         0,                  0},
    {0, 0, 0},
}
Definition at line 41 of file utgarde_pinnacle.cpp.