CMaNGOS_WoTLK: Util.cpp File Reference
Util.cpp File Reference
#include "Util/Util.h"
#include "Util/Timer.h"
#include <utf8.h>
#include "TSS.h"
#include <boost/asio.hpp>
#include <chrono>
#include <cstdarg>
Typedefs
typedef wchar_t const *const * wstrlist
Functions
std::mt19937 * GetRandomGenerator ()
int32 irand (int32 min, int32 max)
uint32 urand (uint32 min, uint32 max)
float frand (float min, float max)
int32 irand ()
uint32 urand ()
double rand_norm ()
float rand_norm_f ()
double rand_chance ()
float rand_chance_f ()
Tokens StrSplit (const std::string &src, const std::string &sep)
uint32 GetUInt32ValueFromArray (Tokens const &data, uint16 index)
float GetFloatValueFromArray (Tokens const &data, uint16 index)
void stripLineInvisibleChars (std::string &str)
tm TimeBreakdown (time_t time)
time_t GetLocalHourTimestamp (time_t time, uint8 hour, bool onlyAfterTime)
std::string secsToTimeString (time_t timeInSecs, bool shortText, bool hoursOnly)
uint32 TimeStringToSecs (const std::string &timestring)
std::string TimeToTimestampStr (time_t t)
time_t timeBitFieldsToSecs (uint32 packedDate)
bool IsIPAddress (char const *ipaddress)
Check if the string is a valid ip address representation.
uint32 CreatePIDFile (const std::string &filename)
create PID file
bool Utf8toWStr (const std::string &utf8str, std::wstring &wstr, size_t max_len)
size_t utf8length (std::string &utf8str)
size_t utf8limit (std::string &utf8str, size_t bytes)
void utf8truncate (std::string &utf8str, size_t len)
bool WStrToUtf8 (const std::wstring &wstr, std::string &utf8str)
std::wstring GetMainPartOfName (const std::wstring &wname, uint32 declension)
bool utf8ToConsole (const std::string &utf8str, std::string &conStr)
bool consoleToUtf8 (const std::string &conStr, std::string &utf8str)
bool Utf8FitTo (const std::string &str, const std::wstring &search)
void utf8printf (FILE *out, const char *str,...)
void vutf8printf (FILE *out, const char *str, va_list *ap)
void hexEncodeByteArray (uint8 *bytes, uint32 arrayLen, std::string &result)
Variables
static MaNGOS::thread_local_ptr< std::mt19937 > mtRand & initRand
Typedef Documentation
wstrlist
typedef wchar_t const* const* wstrlist
Definition at line 443 of file Util.cpp.
Function Documentation
consoleToUtf8()
bool consoleToUtf8 (const std::string & conStr, std::string & utf8str)
Definition at line 508 of file Util.cpp.
References WStrToUtf8().
Referenced by CliRunnable::run().
CreatePIDFile()
uint32 CreatePIDFile (const std::string & filename)
create PID file
Definition at line 311 of file Util.cpp.
Referenced by main(), and Master::Run().
frand()
float frand (float min, float max)
Definition at line 80 of file Util.cpp.
Referenced by FleeingMovementGenerator::_setLocation(), FormationSlotData::AddPositionVariation(), boss_sindragosaAI::DoFrostBomb(), Spell::EffectActivateObject(), Spell::EffectDummy(), EffectDummyCreature_spell_dummy_npc(), Spell::EffectScriptEffect(), Spell::EffectSummonType(), ChaseMovementGenerator::FanOut(), PlayerbotClassAI::FleeFromPointIfCan(), npc_blastmaster_emi_shortfuseAI::JustSummoned(), boss_saraAI::JustSummoned(), spell_strangulating_aura::OnApply(), spell_summon_undead::OnEffectExecute(), NetherVaporLightning::OnPeriodicDummy(), RandomRadiusPicker::OnRadiusCalculate(), npc_trial_grand_championAI::Reset(), npc_champion_mountAI::Reset(), npc_trial_grand_championAI::UpdateAI(), npc_champion_mountAI::UpdateAI(), and npc_shay_leafrunnerAI::UpdateFollowerAI().
GetFloatValueFromArray()
float GetFloatValueFromArray (Tokens const & data, uint16 index)
Definition at line 150 of file Util.cpp.
References GetUInt32ValueFromArray().
GetLocalHourTimestamp()
time_t GetLocalHourTimestamp (time_t time, uint8 hour, bool onlyAfterTime)
Definition at line 196 of file Util.cpp.
References DAY, HOUR, and TimeBreakdown().
Referenced by MapPersistentStateManager::GetSubsequentResetTime().
GetMainPartOfName()
std::wstring GetMainPartOfName (const std::wstring & wname, uint32 declension)
Definition at line 445 of file Util.cpp.
References isCyrillicCharacter().
Referenced by ObjectMgr::CheckDeclinedNames(), WorldSession::HandlePetRename(), and WorldSession::HandleSetPlayerDeclinedNamesOpcode().
GetRandomGenerator()
std::mt19937* GetRandomGenerator ()
Definition at line 37 of file Util.cpp.
Referenced by boss_fankrissAI::Aggro(), npc_anubisath_sentinelAI::Aggro(), boss_kiljaedenAI::DoActivateDragonOrb(), boss_priestess_delrissaAI::DoInitializeCompanions(), instance_scholomance::DoRespawnEntranceRoom(), boss_thorimAI::DoSpawnArenaDwarf(), boss_moroesAI::DoSpawnGuests(), boss_ossirianAI::DoSpawnNextCrystal(), instance_stratholme::DoSpawnScourgeInvaders(), boss_netherspiteAI::DoSummonPortals(), Spell::EffectDummy(), priestess_commonAI::ExecuteAction(), boss_fankrissAI::ExecuteAction(), boss_skeramAI::ExecuteAction(), boss_high_astromancer_solarianAI::ExecuteAction(), PlayerAI::ExecuteSpells(), SpawnGroup::GetEligibleEntry(), WardenScanMgr::GetRandomScans(), boss_skeramAI::HandleInitImages(), boss_high_astromancer_solarianAI::HandleSplitPriests(), ThousandBladesRenataki::OnEffectExecute(), TriggerKTAdd::OnEffectExecute(), ChainsKelThuzad::OnEffectExecute(), WebWrapMaexxna::OnEffectExecute(), SummonZombieChow::OnPeriodicTrigger(), instance_trial_of_the_champion::OnPlayerEnter(), boss_freyaAI::ReceiveAIEvent(), boss_uromAI::Reset(), boss_freyaAI::Reset(), npc_voice_yogg_saronAI::Reset(), boss_ymironAI::Reset(), LootTemplate::LootGroup::Roll(), PoolGroup< T >::RollOne(), SelectRandomFlameshockerSpawnTarget(), instance_violet_hold::SetRandomBosses(), SpawnGroup::Spawn(), WorldState::StartScourgeInvasion(), instance_blackwing_lair::Update(), boss_malygosAI::UpdateAI(), and UnitAI::UpdateSpellLists().
GetUInt32ValueFromArray()
uint32 GetUInt32ValueFromArray (Tokens const & data, uint16 index)
Definition at line 142 of file Util.cpp.
Referenced by Player::BuildEnumData(), GetFloatValueFromArray(), and Corpse::LoadFromDB().
hexEncodeByteArray()
void hexEncodeByteArray (uint8 * bytes, uint32 arrayLen, std::string & result)
Definition at line 567 of file Util.cpp.
Referenced by AccountMgr::CalculateShaPassHash().
irand() [1/2]
int32 irand ()
Definition at line 86 of file Util.cpp.
irand() [2/2]
int32 irand (int32 min, int32 max)
Definition at line 68 of file Util.cpp.
Referenced by boss_warbringer_omroggAI::Aggro(), WorldObject::CalculateSpellEffectValue(), Spell::CheckCast(), boss_warbringer_omroggAI::DoYellForThreat(), EffectDummyCreature_spell_dummy_npc(), Spell::EffectSchoolDMG(), ChaseMovementGenerator::FanOut(), GetItemEnchantMod(), ObjectMgr::GetRandomEntry(), Aura::HandleAuraModShapeshift(), Spell::HandleEffect(), boss_kiljaedenAI::JustDidDialogueStep(), boss_warbringer_omroggAI::KilledUnit(), roll_chance_i(), npc_doomfire_targetingAI::UpdateAI(), boss_bjarngrimAI::UpdateAI(), Player::UpdateSkillPro(), and GameObject::Use().
IsIPAddress()
bool IsIPAddress (char const * ipaddress)
Check if the string is a valid ip address representation.
Definition at line 298 of file Util.cpp.
Referenced by ChatHandler::HandleBanHelper(), ChatHandler::HandleBanInfoIPCommand(), and ChatHandler::HandleUnBanHelper().
rand_chance()
double rand_chance (void)
Definition at line 110 of file Util.cpp.
Referenced by GetItemEnchantMod(), ScriptMgr::GetRandomScriptTemplateId(), roll_chance_f(), and PoolGroup< T >::RollOne().
rand_chance_f()
float rand_chance_f (void)
Definition at line 116 of file Util.cpp.
Referenced by GetExplicitDiscoverySpell(), and LootTemplate::LootGroup::Roll().
rand_norm()
double rand_norm (void)
Definition at line 98 of file Util.cpp.
rand_norm_f()
float rand_norm_f (void)
Definition at line 104 of file Util.cpp.
Referenced by PathFinder::ComputePathToRandomPoint(), Spell::EffectTransmitted(), WorldObject::GetRandomPoint(), Map::GetRandomPointInTheAir(), Map::GetRandomPointUnderWater(), Map::GetReachableRandomPointOnGround(), FlignTorch::OnDestTarget(), Weather::ReGenerate(), Spell::SetTargetMap(), and npc_belnistraszAI::SpawnerSummon().
secsToTimeString()
std::string secsToTimeString (time_t timeInSecs, bool shortText, bool hoursOnly)
Definition at line 211 of file Util.cpp.
References DAY, HOUR, and MINUTE.
Referenced by ChatHandler::HandleBanHelper(), ChatHandler::HandleBanInfoHelper(), ChatHandler::HandleBanInfoIPCommand(), ChatHandler::HandleBanListHelper(), ChatHandler::HandleEventInfoCommand(), ChatHandler::HandleGameObjectTargetCommand(), ChatHandler::HandleInstanceListBindsCommand(), ChatHandler::HandleInstanceUnbindCommand(), WorldSession::HandleMessagechatOpcode(), ChatHandler::HandleNpcInfoCommand(), ChatHandler::HandlePInfoCommand(), ChatHandler::HandleServerInfoCommand(), WorldSession::HandleTextEmoteOpcode(), GMTicketMgr::Print(), GMTicketMgr::ShowMOTD(), and World::ShutdownMsg().
stripLineInvisibleChars()
void stripLineInvisibleChars (std::string & str)
Definition at line 159 of file Util.cpp.
Referenced by WorldSession::CheckChatChannelNameAndPassword(), and WorldSession::CheckChatMessage().
StrSplit()
Tokens StrSplit (const std::string & src, const std::string & sep)
Definition at line 122 of file Util.cpp.
Referenced by MapPersistentStateManager::_DelHelper(), Object::_LoadIntoDataField(), Player::_LoadIntoDataField(), Player::BuildEnumData(), GMTicketMgr::Comment(), MySQLConnection::Initialize(), Taxi::Tracker::Load(), Item::LoadFromDB(), Corpse::LoadFromDB(), CharmInfo::LoadPetActionBar(), PlayerTaxi::LoadTaxiMask(), GMTicketMgr::Print(), BattleGroundMgr::RewardArenaSeason(), and RealmList::UpdateRealm().
timeBitFieldsToSecs()
time_t timeBitFieldsToSecs (uint32 packedDate)
Definition at line 282 of file Util.cpp.
Referenced by WorldSession::HandleCalendarAddEvent(), WorldSession::HandleCalendarCopyEvent(), and WorldSession::HandleCalendarUpdateEvent().
TimeBreakdown()
tm TimeBreakdown (time_t time)
Definition at line 190 of file Util.cpp.
Referenced by GetLocalHourTimestamp().
TimeStringToSecs()
uint32 TimeStringToSecs (const std::string & timestring)
Definition at line 234 of file Util.cpp.
References DAY, HOUR, and MINUTE.
Referenced by ChatHandler::HandleBanHelper().
TimeToTimestampStr()
std::string TimeToTimestampStr (time_t t)
Definition at line 266 of file Util.cpp.
Referenced by GMTicketMgr::Comment(), WorldSession::HandleCalendarGetCalendar(), ChatHandler::HandleCharacterDeletedListHelper(), ChatHandler::HandleEventInfoCommand(), GMTicketMgr::Print(), and ChatHandler::ShowAchievementListHelper().
urand() [1/2]
uint32 urand ()
Definition at line 92 of file Util.cpp.
urand() [2/2]
uint32 urand (uint32 min, uint32 max)
Definition at line 74 of file Util.cpp.
Referenced by mob_water_globuleAI::AcquireNewTarget(), boss_algalonAI::ActivateRandomConstellation(), PlayerbotAI::AddAuction(), UnitAI::AddInitialCooldowns(), AuctionHouseBot::AddLootToItemMap(), boss_swamplord_muselekAI::Aggro(), boss_plugger_spazzringAI::Aggro(), boss_emperor_dagran_thaurissanAI::Aggro(), boss_kazzakAI::Aggro(), boss_aranAI::Aggro(), npc_muglashAI::Aggro(), npc_magwinAI::Aggro(), npc_thrall_old_hillsbradAI::Aggro(), npc_volcorAI::Aggro(), npc_oox22feAI::Aggro(), npc_clintar_dw_spiritAI::Aggro(), npc_oox17tnAI::Aggro(), npc_anubisath_defenderAI::Aggro(), npc_bonker_togglevoltAI::Aggro(), npc_proudhoofAI::Aggro(), npc_father_kamarosAI::Aggro(), boss_bronjahmAI::Aggro(), boss_exarch_maladaarAI::Aggro(), boss_nexusprince_shaffarAI::Aggro(), boss_pandemoniusAI::Aggro(), boss_darkweaver_sythAI::Aggro(), boss_talon_king_ikissAI::Aggro(), boss_ambassador_hellmawAI::Aggro(), boss_blackheart_the_inciterAI::Aggro(), boss_grandmaster_vorpilAI::Aggro(), boss_doomlordkazzakAI::Aggro(), boss_lady_vashjAI::Aggro(), boss_thespiaAI::Aggro(), boss_mekgineer_steamriggerAI::Aggro(), boss_warlord_kalithreshAI::Aggro(), boss_the_makerAI::Aggro(), boss_vazrudenAI::Aggro(), boss_omor_the_unscarredAI::Aggro(), boss_watchkeeper_gargolmarAI::Aggro(), boss_warchief_kargath_bladefistAI::Aggro(), npc_shattered_hand_legionnaire::Aggro(), npc_protectorate_demolitionistAI::Aggro(), boss_highlord_kruulAI::Aggro(), npc_marshal_windsorAI::Aggro(), npc_00x09hlAI::Aggro(), npc_rinjiAI::Aggro(), npc_dorius_stonetenderAI::Aggro(), npc_prospector_remtravelAI::Aggro(), npc_stinky_ignatzAI::Aggro(), npc_captured_arkonarinAI::Aggro(), npc_willix_the_importerAI::Aggro(), npc_giltharesAI::Aggro(), npc_ame01AI::Aggro(), npc_squad_leaderAI::Aggro(), mob_fel_orc_convertAI::Aggro(), mob_lumpAI::Aggro(), npc_kindal_moonweaverAI::Aggro(), guardAI::Aggro(), npc_deathstalker_erlandAI::Aggro(), npc_galen_goodwardAI::Aggro(), npc_defias_traitorAI::Aggro(), boss_veknilashAI::Aggro(), boss_veklorAI::Aggro(), mob_shadowmoon_channelerAI::Aggro(), mob_bt_battle_fighterAI::Aggro(), BossAI::Aggro(), BattleGroundSA::AlterTeleportLocation(), AreaTrigger_at_beggar(), AreaTrigger_at_frostworn_general(), npc_blastmaster_emi_shortfuseAI::AttackedBy(), npc_belnistraszAI::AttackedBy(), npc_dragonmaw_racer_mulverickAI::AttackPlayer(), npc_dragonmaw_racer_skyshatterAI::AttackPlayer(), boss_plugger_spazzringAI::AttackThief(), npc_lazy_peonAI::Awaken(), boss_highlord_kruulAI::boss_highlord_kruulAI(), boss_moorabiAI::boss_moorabiAI(), boss_twin_emperorsAI::boss_twin_emperorsAI(), boss_veklorAI::boss_veklorAI(), boss_veknilashAI::boss_veknilashAI(), boss_vemAI::boss_vemAI(), boss_yaujAI::boss_yaujAI(), Unit::CalculateDamage(), Unit::CalculateGlanceAmount(), npc_shattered_hand_legionnaire::CallForReinforcements(), Creature::ChooseDisplayId(), GossipNPCAI::ChooseEvent(), npc_bt_battle_sensor::ChooseIllidariAttack(), npc_bt_battle_sensor::ChooseIllidariNotRavagers3or4(), npc_bt_battle_sensor::ChooseIllidariRavagers3or4(), UnitAI::ChooseTarget(), FormationMap::claimFormationMarker(), npc_ringoAI::ClearFaint(), boss_majordomoAI::CorpseRemoved(), BattleGroundMgr::CreateNewBattleGround(), npc_apexis_flayerAI::CrystalStrike(), boss_fjolaAI::DoCastSpecialAbility(), npc_ranshallaAI::DoChannelTorchSpell(), npc_tipsy_mcmanusAI::DoCheckDistillationTask(), npc_ranshallaAI::DoContinueEscort(), boss_mimironAI::DoFlyToNextRandomSeat(), npc_graufAI::DoHandleBreathYell(), boss_lady_vashjAI::DoInformGeneratorStopped(), boss_malacrassAI::DoInitializeAdds(), boss_galdarahAI::DoPhaseSwitch(), boss_alarAI::DoPlatformMove(), instance_scholomance::DoRespawnEntranceRoom(), boss_gathios_the_shattererAI::DoSelectCouncilMember(), instance_trial_of_the_crusader::DoSelectCrusaders(), boss_selin_fireheartAI::DoSelectNearestCrystal(), boss_lady_deathwhisperAI::DoSelectRandomCultist(), instance_blackrock_spire::DoSendNextFlamewreathWave(), instance_halls_of_reflection::DoSendNextSpiritWave(), instance_azjol_nerub::DoSendWatcherOrKrikthir(), boss_taldaramAI::DoSetSpheresInMotion(), npc_simon_game_bunnyAI::DoSetupLevel(), world_map_eastern_kingdoms::DoSpawn(), boss_thorimAI::DoSpawnArenaDwarf(), npc_wildaAI::DoSpawnAssassin(), instance_violet_hold::DoSpawnIntroMob(), instance_dark_portal::DoSpawnNextPortal(), instance_culling_of_stratholme::DoSpawnNextScourgeWave(), instance_stratholme::DoSpawnPlaguedCritters(), npc_forest_frogAI::DoSpawnRandom(), instance_stratholme::DoSpawnScourgeInvaders(), boss_uromAI::DoSpawnTrashPack(), instance_pit_of_saron::DoSpawnTyrannusUndead(), mob_illidari_councilAI::DoStartEvent(), npc_time_riftAI::DoSummon(), boss_anzuAI::DoSummonBroodsOfAnzu(), boss_trollgoreAI::DoSummonDrakkariInvaders(), boss_lajAI::DoSummons(), boss_high_botanist_freywinnAI::DoSummonSeedling(), boss_high_astromancer_solarianAI::DoSummonSpotlights(), npc_eris_havenfireAI::DoSummonWave(), hyjalAI::DoTalk(), boss_grand_warlock_nethekurseAI::DoTauntPeons(), instance_zulaman::DoTimeRunSay(), boss_lajAI::DoTransform(), npc_manaforge_control_consoleAI::DoWaveSpawnForCreature(), boss_grand_warlock_nethekurseAI::DoYellForPeonAggro(), boss_grand_warlock_nethekurseAI::DoYellForPeonDeath(), Spell::EffectActivateObject(), EffectAuraDummy_spell_aura_dummy_npc(), Spell::EffectDummy(), EffectDummyCreature_npc_city_guard(), EffectDummyCreature_spell_boss_thermaplugg(), EffectDummyCreature_spell_dummy_npc(), EffectDummyGameObj_spell_dummy_go(), Spell::EffectEnergize(), Spell::EffectPickPocket(), Spell::EffectScriptEffect(), EffectScriptEffectCreature_npc_putricide(), Spell::EffectSummonPet(), Spell::EffectSummonType(), Spell::EffectTeleportUnits(), Spell::EffectTransmitted(), Spell::EffectTriggerSpell(), boss_ichoronAI::EndSplitPhase(), npc_thrall_old_hillsbradAI::EnterEvadeMode(), hyjalAI::EventStarted(), npc_sunblade_scoutAI::ExecuteAction(), npc_sunblade_protectorAI::ExecuteAction(), mob_ohganAI::ExecuteAction(), boss_ahuneAI::ExecuteAction(), boss_alarAI::ExecuteAction(), boss_broodlordAI::ExecuteAction(), boss_ebonrocAI::ExecuteAction(), boss_firemawAI::ExecuteAction(), boss_flamegorAI::ExecuteAction(), boss_nefarianAI::ExecuteAction(), boss_razorgoreAI::ExecuteAction(), boss_vaelastraszAI::ExecuteAction(), boss_victor_nefariusAI::ExecuteAction(), npc_dawnblade_blood_knight::ExecuteAction(), boss_curatorAI::ExecuteAction(), boss_maiden_of_virtueAI::ExecuteAction(), boss_attumenAI::ExecuteAction(), boss_nightbaneAI::ExecuteAction(), boss_malchezaarAI::ExecuteAction(), boss_aranAI::ExecuteAction(), boss_terestianAI::ExecuteAction(), boss_felblood_kaelthasAI::ExecuteAction(), priestess_commonAI::ExecuteAction(), boss_priestess_delrissaAI::ExecuteAction(), npc_kagani_nightstrikeAI::ExecuteAction(), npc_ellrys_duskhallowAI::ExecuteAction(), npc_eramas_brightblazeAI::ExecuteAction(), npc_yazzaiAI::ExecuteAction(), npc_warlord_salarisAI::ExecuteAction(), npc_garaxxasAI::ExecuteAction(), npc_apokoAI::ExecuteAction(), npc_zelfanAI::ExecuteAction(), boss_garrAI::ExecuteAction(), boss_gehennasAI::ExecuteAction(), boss_lucifronAI::ExecuteAction(), boss_magmadarAI::ExecuteAction(), boss_majordomoAI::ExecuteAction(), boss_ragnarosAI::ExecuteAction(), boss_shazzrahAI::ExecuteAction(), boss_sulfuronAI::ExecuteAction(), mob_flamewaker_priestAI::ExecuteAction(), npc_highlord_darion_mograineAI::ExecuteAction(), boss_high_inquisitor_whitemaneAI::ExecuteAction(), mob_arugal_voidwalkerAI::ExecuteAction(), boss_arugalAI::ExecuteAction(), boss_brutallusAI::ExecuteAction(), boss_alythessAI::ExecuteAction(), boss_sacrolashAI::ExecuteAction(), boss_felmystAI::ExecuteAction(), boss_kalecgosAI::ExecuteAction(), boss_sathrovarrAI::ExecuteAction(), boss_kiljaedenAI::ExecuteAction(), npc_sinister_reflectionAI::ExecuteAction(), boss_entropiusAI::ExecuteAction(), boss_akilzonAI::ExecuteAction(), boss_halazziAI::ExecuteAction(), boss_spirit_lynxAI::ExecuteAction(), boss_nalorakkAI::ExecuteAction(), boss_zuljinAI::ExecuteAction(), boss_azuregosAI::ExecuteAction(), boss_anetheronAI::ExecuteAction(), boss_archimondeAI::ExecuteAction(), boss_kazrogalAI::ExecuteAction(), boss_rage_winterchillAI::ExecuteAction(), hyjalAI::ExecuteAction(), npc_jaina_proudmooreAI::ExecuteAction(), npc_thrallAI::ExecuteAction(), npc_tyrande_whisperwindAI::ExecuteAction(), boss_ayamissAI::ExecuteAction(), boss_kurinnaxxAI::ExecuteAction(), boss_ossirianAI::ExecuteAction(), npc_general_andorovAI::ExecuteAction(), npc_kaldorei_eliteAI::ExecuteAction(), boss_kriAI::ExecuteAction(), boss_vemAI::ExecuteAction(), boss_yaujAI::ExecuteAction(), boss_eye_of_cthunAI::ExecuteAction(), boss_fankrissAI::ExecuteAction(), boss_huhuranAI::ExecuteAction(), boss_sarturaAI::ExecuteAction(), boss_skeramAI::ExecuteAction(), boss_twin_emperorsAI::ExecuteAction(), boss_veknilashAI::ExecuteAction(), boss_veklorAI::ExecuteAction(), boss_viscidusAI::ExecuteAction(), npc_anubisath_defenderAI::ExecuteAction(), boss_hadronoxAI::ExecuteAction(), boss_krikthirAI::ExecuteAction(), npc_nerubian_burrowerAI::ExecuteAction(), npc_living_mojoAI::ExecuteAction(), boss_sladranAI::ExecuteAction(), boss_bronjahmAI::ExecuteAction(), boss_ickAI::ExecuteAction(), boss_tyrannusAI::ExecuteAction(), boss_lady_deathwhisperAI::ExecuteAction(), boss_anomalusAI::ExecuteAction(), boss_ormorokAI::ExecuteAction(), boss_telestraAI::ExecuteAction(), boss_eregosAI::ExecuteAction(), boss_ingvarAI::ExecuteAction(), mob_dragonflayer_forge_masterAI::ExecuteAction(), boss_skadiAI::ExecuteAction(), boss_svalaAI::ExecuteAction(), boss_ichoronAI::ExecuteAction(), boss_xevozzAI::ExecuteAction(), boss_shirrakAI::ExecuteAction(), boss_nexusprince_shaffarAI::ExecuteAction(), npc_bonechewer_brawler::ExecuteAction(), boss_gurtogg_bloodboilAI::ExecuteAction(), boss_illidan_stormrageAI::ExecuteAction(), npc_akama_illidanAI::ExecuteAction(), boss_maievAI::ExecuteAction(), boss_shahrazAI::ExecuteAction(), boss_teron_gorefiendAI::ExecuteAction(), boss_najentusAI::ExecuteAction(), boss_gathios_the_shattererAI::ExecuteAction(), boss_high_nethermancer_zerevorAI::ExecuteAction(), boss_lady_malandeAI::ExecuteAction(), boss_fathomguard_sharkkisAI::ExecuteAction(), boss_fathomguard_tidalvessAI::ExecuteAction(), boss_lady_vashjAI::ExecuteAction(), boss_leotheras_the_blindAI::ExecuteAction(), boss_morogrim_tidewalkerAI::ExecuteAction(), boss_the_lurker_belowAI::ExecuteAction(), boss_hungarfenAI::ExecuteAction(), boss_swamplord_muselekAI::ExecuteAction(), boss_gruulAI::ExecuteAction(), boss_high_king_maulgarAI::ExecuteAction(), boss_olm_the_summonerAI::ExecuteAction(), boss_kiggler_the_crazedAI::ExecuteAction(), boss_blindeye_the_seerAI::ExecuteAction(), boss_broggokAI::ExecuteAction(), boss_kelidan_the_breakerAI::ExecuteAction(), mob_shadowmoon_channelerAI::ExecuteAction(), boss_the_makerAI::ExecuteAction(), boss_vazruden_heraldAI::ExecuteAction(), boss_vazrudenAI::ExecuteAction(), boss_omor_the_unscarredAI::ExecuteAction(), boss_magtheridonAI::ExecuteAction(), mob_hellfire_channelerAI::ExecuteAction(), npc_shattered_hand_legionnaire::ExecuteAction(), npc_razorthorn_ravager::ExecuteAction(), boss_high_astromancer_solarianAI::ExecuteAction(), boss_void_reaverAI::ExecuteAction(), npc_burster_wormAI::ExecuteAction(), ScourgeMinion::ExecuteAction(), PallidHorrorAI::ExecuteAction(), boss_kazzakAI::ExecuteActions(), boss_kaelthasAI::ExecuteActions(), boss_anzuAI::ExecuteActions(), ScriptAction::ExecuteDbscriptCommand(), PlayerAI::ExecuteSpells(), Spell::FillTargetMap(), Spell::FilterTargetMap(), World::GenerateEventGroupEvents(), Loot::GenerateMoneyLoot(), ObjectMgr::GeneratePetName(), GossipNPCAppearanceAllSpiritOfCompetition::GetAuraScriptCustomizationValue(), GossipNPCAppearanceAllPirateDay::GetAuraScriptCustomizationValue(), NamreebAnticheat::AnticheatConfig::GetBanDelay(), ObjectMgr::GetCreatureCooldown(), ObjectMgr::GetCreatureModelRandomGender(), SpawnGroup::GetEligibleEntry(), boss_anzuAI::GetInitialActionTimer(), boss_kazzakAI::GetInitialActionTimer(), boss_azgalorAI::GetInitialActionTimer(), boss_kazrogalAI::GetInitialActionTimer(), boss_rage_winterchillAI::GetInitialActionTimer(), boss_warlord_kalithreshAI::GetInitialActionTimer(), mob_bt_battle_fighterAI::GetInitialActionTimer(), boss_highlord_kruulAI::GetInitialActionTimer(), boss_essence_of_desireAI::GetInitialActionTimer(), boss_dorotheeAI::GetInitialActionTimer(), boss_teron_gorefiendAI::GetInitialActionTimer(), boss_gurtogg_bloodboilAI::GetInitialActionTimer(), boss_illidan_stormrageAI::GetInitialActionTimer(), boss_shahrazAI::GetInitialActionTimer(), boss_supremusAI::GetInitialActionTimer(), boss_temporusAI::GetInitialActionTimer(), boss_terokkAI::GetInitialActionTimer(), npc_skyguard_rangerAI::GetInitialActionTimer(), npc_apexis_flayerAI::GetInitialActionTimer(), NamreebAnticheat::AnticheatConfig::GetIPBanDelay(), NamreebAnticheat::AnticheatConfig::GetKickDelay(), WardenModuleMgr::GetMacModule(), Unit::GetNextRandomRaidMember(), boss_thorimAI::GetRandomArenaPlayer(), instance_pinnacle::GetRandomBrazier(), instance_violet_hold::GetRandomMobForNormalPortal(), instance_culling_of_stratholme::GetRandomMobOfType(), FormationMap::getRandomOccupant(), instance_violet_hold::GetRandomPortalEliteEntry(), CreatureData::GetRandomRespawnTime(), GameObjectData::GetRandomRespawnTime(), ScriptMgr::GetRandomScriptTemplateId(), boss_sacrolashAI::GetRandomTargetAtDist(), GetRandomText(), GetRandomWavePath(), Creature::GetSpellCooldown(), npc_magister_aledisAI::GetSubsequentActionTimer(), boss_anzuAI::GetSubsequentActionTimer(), boss_blackheart_the_inciterAI::GetSubsequentActionTimer(), boss_kazzakAI::GetSubsequentActionTimer(), boss_moroesAI::GetSubsequentActionTimer(), boss_anetheronAI::GetSubsequentActionTimer(), boss_archimondeAI::GetSubsequentActionTimer(), boss_azgalorAI::GetSubsequentActionTimer(), boss_kazrogalAI::GetSubsequentActionTimer(), boss_rage_winterchillAI::GetSubsequentActionTimer(), boss_talon_king_ikissAI::GetSubsequentActionTimer(), boss_warlord_kalithreshAI::GetSubsequentActionTimer(), boss_black_stalkerAI::GetSubsequentActionTimer(), boss_swamplord_muselekAI::GetSubsequentActionTimer(), mob_bt_battle_fighterAI::GetSubsequentActionTimer(), boss_highlord_kruulAI::GetSubsequentActionTimer(), boss_dorotheeAI::GetSubsequentActionTimer(), boss_watchkeeper_gargolmarAI::GetSubsequentActionTimer(), boss_teron_gorefiendAI::GetSubsequentActionTimer(), boss_gurtogg_bloodboilAI::GetSubsequentActionTimer(), boss_maievAI::GetSubsequentActionTimer(), npc_nether_rayAI::GetSubsequentActionTimer(), boss_nexusprince_shaffarAI::GetSubsequentActionTimer(), boss_shahrazAI::GetSubsequentActionTimer(), boss_supremusAI::GetSubsequentActionTimer(), boss_temporusAI::GetSubsequentActionTimer(), boss_terokkAI::GetSubsequentActionTimer(), npc_corrupted_furbolgAI::GetSubsequentActionTimer(), boss_maiden_of_virtueAI::GetSubsequentActionTimer(), boss_midnightAI::GetSubsequentActionTimer(), boss_attumenAI::GetSubsequentActionTimer(), boss_terestianAI::GetSubsequentActionTimer(), boss_selin_fireheartAI::GetSubsequentActionTimer(), boss_scarlet_commander_mograineAI::GetSubsequentActionTimer(), boss_high_inquisitor_whitemaneAI::GetSubsequentActionTimer(), npc_skyguard_rangerAI::GetSubsequentActionTimer(), npc_apexis_flayerAI::GetSubsequentActionTimer(), boss_yorAI::GetSubsequentActionTimer(), instance_draktharon_keep::GetSummonDummy(), npc_chess_piece_genericAI::GetTargetByType(), WardenModuleMgr::GetWindowsModule(), world_map_kalimdor::GhostOPlasmEventStep(), GossipSelect_npc_death_knight_initiate(), GossipSelect_npc_saronite_mine_slave(), GossipSelect_npc_tobias_seecher(), GOUse_go_mysterious_snow_mound(), GOUse_go_ossirian_crystal(), GOUse_go_strange_pool(), WorldState::HandleActiveZone(), npc_disobedient_dragonmaw_peonAI::HandleAngry(), boss_kiljaedenAI::HandleAttackDelay(), Aura::HandleAuraDummy(), instance_blackrock_depths::HandleBarPatrons(), world_map_outland::HandleBashirEnemyAttack(), npc_disobedient_dragonmaw_peonAI::HandleBooterang(), boss_lady_vashjAI::HandleCoilfangElite(), boss_lady_vashjAI::HandleCoilfangStrider(), Unit::HandleDamageDealt(), boss_felmystAI::HandleDemonicVapor(), Unit::HandleDummyAuraProc(), boss_ahuneAI::HandleEmerge(), boss_lady_vashjAI::HandleEnchantedElemental(), boss_eye_of_cthunAI::HandleEndDarkGlare(), WorldState::HandleExternalEvent(), boss_skeramAI::HandleInitImages(), instance_ahnkahet::HandleInsanitySwitch(), boss_brutallusAI::HandleMadrigosaFrostbolt(), Aura::HandleModPossess(), boss_archimondeAI::HandleOutro(), boss_telestraAI::HandlePersonalityMerge(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCastSpellOpcode(), boss_vazruden_heraldAI::HandlePhaseChange(), boss_nightbaneAI::HandlePhaseTransition(), boss_ragnarosAI::HandlePhaseTransition(), boss_illidan_stormrageAI::HandlePhaseTransition(), boss_leotheras_the_blindAI::HandlePhaseTransition(), boss_alarAI::HandlePhaseTransition(), boss_felmystAI::HandlePreBreath(), WorldSession::HandleRandomRollOpcode(), NecroticShard::HandleShardMinionSpawnerSmall(), world_map_outland::HandleShartuulAddSpawns(), boss_high_astromancer_solarianAI::HandleSplitPhaseDelay(), boss_high_astromancer_solarianAI::HandleSplitPriests(), boss_lady_vashjAI::HandleSporebat(), boss_lady_vashjAI::HandleTaintedElemental(), boss_heiganAI::HandleTaunt(), boss_felmystAI::HandleTransitionDelay(), hyjalAI::hyjalAI(), npc_highlord_darion_mograineAI::JustDidDialogueStep(), boss_kiljaedenAI::JustDidDialogueStep(), npc_anchorite_baradaAI::JustDidDialogueStep(), instance_arcatraz::JustDidDialogueStep(), npc_thrall_old_hillsbradAI::JustDied(), boss_volazjAI::JustDied(), boss_brundirAI::JustDied(), boss_molgeimAI::JustDied(), boss_steelbreakerAI::JustDied(), PallidHorrorAI::JustDied(), BossAI::JustDied(), npc_human_footmanAI::JustDied(), npc_orc_gruntAI::JustDied(), mob_webbed_creatureAI::JustDied(), mob_netherweb_victimAI::JustDied(), npc_shattered_sun_fighterAI::JustRespawned(), npc_soulflayerAI::JustRespawned(), npc_magrami_spectre::JustRespawned(), npc_skyguard_prisonerAI::JustRespawned(), boss_highlord_kruulAI::JustRespawned(), npc_thrall_old_hillsbradAI::JustSummoned(), npc_credit_marker_they_must_burnAI::JustSummoned(), npc_skyguard_prisonerAI::JustSummoned(), boss_curatorAI::JustSummoned(), boss_midnightAI::JustSummoned(), boss_ayamissAI::JustSummoned(), npc_ethereal_frostworgAI::JustSummoned(), boss_terokkAI::JustSummoned(), CombatAI::KilledUnit(), boss_aranAI::KilledUnit(), npc_arthasAI::KilledUnit(), boss_aeonusAI::KilledUnit(), boss_chrono_lord_dejaAI::KilledUnit(), npc_thrall_old_hillsbradAI::KilledUnit(), boss_jedogaAI::KilledUnit(), boss_nadoxAI::KilledUnit(), boss_taldaramAI::KilledUnit(), boss_volazjAI::KilledUnit(), boss_anubarakAI::KilledUnit(), boss_eadricAI::KilledUnit(), boss_paletressAI::KilledUnit(), boss_black_knightAI::KilledUnit(), boss_tharonjaAI::KilledUnit(), boss_moorabiAI::KilledUnit(), boss_blood_queen_lanathelAI::KilledUnit(), boss_festergutAI::KilledUnit(), boss_professor_putricideAI::KilledUnit(), boss_sindragosaAI::KilledUnit(), boss_malygosAI::KilledUnit(), boss_uromAI::KilledUnit(), boss_varosAI::KilledUnit(), boss_sartharionAI::KilledUnit(), mob_tenebronAI::KilledUnit(), mob_shadronAI::KilledUnit(), mob_vesperonAI::KilledUnit(), boss_bjarngrimAI::KilledUnit(), boss_ionarAI::KilledUnit(), boss_lokenAI::KilledUnit(), boss_volkhanAI::KilledUnit(), npc_brann_hosAI::KilledUnit(), boss_brundirAI::KilledUnit(), boss_molgeimAI::KilledUnit(), boss_steelbreakerAI::KilledUnit(), boss_auriayaAI::KilledUnit(), boss_flame_leviathanAI::KilledUnit(), boss_general_vezaxAI::KilledUnit(), boss_ymironAI::KilledUnit(), boss_exarch_maladaarAI::KilledUnit(), boss_nexusprince_shaffarAI::KilledUnit(), boss_pandemoniusAI::KilledUnit(), boss_darkweaver_sythAI::KilledUnit(), boss_talon_king_ikissAI::KilledUnit(), boss_ambassador_hellmawAI::KilledUnit(), boss_grandmaster_vorpilAI::KilledUnit(), boss_fathomlord_karathressAI::KilledUnit(), boss_hydross_the_unstableAI::KilledUnit(), boss_lady_vashjAI::KilledUnit(), boss_morogrim_tidewalkerAI::KilledUnit(), boss_thespiaAI::KilledUnit(), boss_mekgineer_steamriggerAI::KilledUnit(), boss_warlord_kalithreshAI::KilledUnit(), boss_swamplord_muselekAI::KilledUnit(), boss_kelidan_the_breakerAI::KilledUnit(), boss_the_makerAI::KilledUnit(), boss_vazrudenAI::KilledUnit(), boss_omor_the_unscarredAI::KilledUnit(), boss_watchkeeper_gargolmarAI::KilledUnit(), boss_grand_warlock_nethekurseAI::KilledUnit(), npc_wounded_blood_elfAI::KilledUnit(), npc_millhouse_manastormAI::KilledUnit(), boss_dalliahAI::KilledUnit(), boss_high_botanist_freywinnAI::KilledUnit(), boss_warp_splinterAI::KilledUnit(), boss_kaelthasAI::KilledUnit(), boss_nethermancer_sepethreaAI::KilledUnit(), boss_pathaleon_the_calculatorAI::KilledUnit(), boss_vaelastraszAI::KilledUnit(), boss_kazzakAI::KilledUnit(), boss_anubarak_trialAI::KilledUnit(), trial_crusader_commonAI::KilledUnit(), boss_jaraxxusAI::KilledUnit(), boss_fjolaAI::KilledUnit(), boss_eydisAI::KilledUnit(), boss_devourer_of_soulsAI::KilledUnit(), boss_valanar_iccAI::KilledUnit(), boss_keleseth_iccAI::KilledUnit(), boss_taldaram_iccAI::KilledUnit(), boss_lord_marrowgarAI::KilledUnit(), boss_rotfaceAI::KilledUnit(), boss_halion_realAI::KilledUnit(), boss_halion_twilightAI::KilledUnit(), boss_savianaAI::KilledUnit(), boss_algalonAI::KilledUnit(), boss_freyaAI::KilledUnit(), boss_hodirAI::KilledUnit(), boss_ignisAI::KilledUnit(), boss_kologarnAI::KilledUnit(), boss_leviathan_mk2AI::KilledUnit(), boss_vx001AI::KilledUnit(), boss_aerial_unitAI::KilledUnit(), boss_thorimAI::KilledUnit(), boss_xt_002AI::KilledUnit(), boss_saraAI::KilledUnit(), boss_doomlordkazzakAI::KilledUnit(), boss_doomwalkerAI::KilledUnit(), boss_warchief_kargath_bladefistAI::KilledUnit(), boss_harbinger_skyrissAI::KilledUnit(), boss_mechano_lord_capacitusAI::KilledUnit(), boss_the_lich_king_iccAI::KilledUnit(), boss_ickAI::KilledUnit(), boss_krickAI::KilledUnit(), boss_tyrannusAI::KilledUnit(), boss_nefarianAI::KilledUnit(), boss_krikthirAI::KilledUnit(), boss_bronjahmAI::KilledUnit(), boss_deathbringer_saurfangAI::KilledUnit(), boss_lady_deathwhisperAI::KilledUnit(), boss_kelthuzadAI::KilledUnit(), boss_anomalusAI::KilledUnit(), boss_keristraszaAI::KilledUnit(), boss_ormorokAI::KilledUnit(), boss_telestraAI::KilledUnit(), boss_eregosAI::KilledUnit(), boss_baltharusAI::KilledUnit(), boss_zarithrianAI::KilledUnit(), boss_sjonnirAI::KilledUnit(), boss_ingvarAI::KilledUnit(), boss_skadiAI::KilledUnit(), boss_svalaAI::KilledUnit(), boss_leotheras_the_blindAI::KilledUnit(), boss_high_astromancer_solarianAI::KilledUnit(), boss_void_reaverAI::KilledUnit(), boss_ichoronAI::KilledUnit(), boss_xevozzAI::KilledUnit(), Creature::LoadFromDB(), Loot::Loot(), LootItem::LootItem(), boss_novosAI::LostOneCrystal(), Unit::MagicSpellHitResult(), Unit::MeleeSpellHitResult(), mob_scarlet_traineeAI::mob_scarlet_traineeAI(), ChatHandler::ModifyMountCommandHelper(), MouthAI::MouthAI(), npc_draenei_survivorAI::MoveInLineOfSight(), npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), npc_shay_leafrunnerAI::MoveInLineOfSight(), boss_jedogaAI::MoveInLineOfSight(), boss_krikthirAI::MoveInLineOfSight(), npc_volatile_ooze_iccAI::MoveInLineOfSight(), npc_gas_cloud_iccAI::MoveInLineOfSight(), npc_supplicantAI::MoveInLineOfSight(), npc_harkorAI::MoveInLineOfSight(), npc_ashliAI::MoveInLineOfSight(), boss_ossirianAI::MoveInLineOfSight(), boss_anubrekhanAI::MoveInLineOfSight(), NetherCharge::MovementInform(), npc_akama_illidanAI::MovementInform(), mob_soaring_eagleAI::MovementInform(), npc_lazy_peonAI::MovementInform(), npc_concentrated_bulletAI::MovementInform(), npc_rookery_hatcherAI::MovementInform(), boss_jedogaAI::MovementInform(), npc_dragonmaw_peonAI::MovementInform(), NetherCharge::MoveToRandomPoint(), npc_akama_illidanAI::npc_akama_illidanAI(), npc_disruptor_towerAI::npc_disruptor_towerAI(), npc_ethereal_frostworgAI::npc_ethereal_frostworgAI(), npc_grimstoneAI::npc_grimstoneAI(), npc_nether_vaporAI::npc_nether_vaporAI(), spell_lingering_fumes_targetting::OnAfterHit(), DarknessOfSouls::OnApply(), BrewfestBarkerBunny::OnApply(), GDRPeriodicDamage::OnAuraValueCalculate(), FaceRandomTarget::OnCast(), RibbonPoleDancerCheck::OnCast(), instance_blackrock_depths::OnCreatureDeath(), instance_blackrock_spire::OnCreatureDeath(), instance_karazhan::OnCreatureDeath(), instance_pit_of_saron::OnCreatureDeath(), spell_launch_harpoon::OnEffectExecute(), DestroyEgg::OnEffectExecute(), spell_gift_of_the_harvester::OnEffectExecute(), spell_valentine_boss_validate_area::OnEffectExecute(), RotateTrigger::OnEffectExecute(), AQWhirlwind::OnEffectExecute(), spell_wailing_souls::OnEffectExecute(), spell_bone_spike_graveyard_storm::OnEffectExecute(), PolarityShift::OnEffectExecute(), ThrowTorch::OnEffectExecute(), WondervoltTrap::OnEffectExecute(), RighteousDefense::OnEffectExecute(), ChainsKelThuzad::OnEffectExecute(), WebWrapMaexxna::OnEffectExecute(), PotCheck::OnEffectExecute(), LeoWhirlwindProc::OnEffectExecute(), Spout::OnEffectExecute(), QuakeMagth::OnEffectExecute(), CursedScarabPeriodicTrigger::OnEffectExecute(), TestRibbonPoleChannelTrigger::OnEffectExecute(), RevelerApplauseCheer::OnEffectExecute(), ImpInABottleSay::OnEffectExecute(), HorsemanConflagrateTargetTest::OnEffectExecute(), DawnbladeAttack::OnEffectExecute(), FlameSear::OnInit(), LightningWhirl::OnInit(), LightningWhirlHeroic::OnInit(), go_ai_suppression::OnLootStateChange(), Player::OnMirrorTimerExpirationPulse(), ForsakenSkill::OnPeriodicDummy(), TransformVisualPeriodic::OnPeriodicDummy(), spell_summon_anubar_periodic_aura::OnPeriodicDummy(), spell_soulstorm_visual_aura::OnPeriodicDummy(), spell_crystal_spike_aura::OnPeriodicDummy(), spell_splatter_aura::OnPeriodicDummy(), RandomIngredientAura::OnPeriodicDummy(), AllergiesAura::OnPeriodicDummy(), KillingSpree::OnPeriodicDummy(), Armageddon::OnPeriodicTrigger(), EarthquakeGuardian::OnPeriodicTrigger(), SummonSkeletonsNoth::OnPeriodicTrigger(), instance_karazhan::OnPlayerEnter(), instance_trial_of_the_champion::OnPlayerEnter(), Icecrown25MeleeTrinket::OnProc(), boss_kelthuzadAI::OnSpellCast(), boss_felmystAI::OnSpellCooldownAdded(), boss_azgalorAI::OnSpellCooldownAdded(), npc_venture_co_lookoutAI::OnStealthAlert(), Aura::PeriodicDummyTick(), npc_ouro_moundAI::PickNewTarget(), PickRandomValue(), Pet::PlayDismissSound(), Player::Player(), GroupLootRoll::PlayerVote(), LFGQueueData::PopQueue(), Spell::ProcessDispelList(), CreatureEventAI::ProcessEvent(), instance_halls_of_stone::ProcessFaceSpell(), instance_halls_of_stone::ProcessFaceSummon(), BossAI::RandomTimer(), boss_illidan_stormrageAI::ReceiveAIEvent(), boss_maievAI::ReceiveAIEvent(), boss_moroesAI::ReceiveAIEvent(), boss_kiljaedenAI::ReceiveAIEvent(), boss_murmurAI::ReceiveAIEvent(), boss_magtheridonAI::ReceiveAIEvent(), npc_sinister_reflectionAI::ReceiveAIEvent(), npc_bonechewer_brawler::ReceiveAIEvent(), boss_alarAI::ReceiveAIEvent(), npc_scarlet_ghoulAI::ReceiveAIEvent(), boss_crusader_druid_balanceAI::ReceiveAIEvent(), boss_crusader_hunterAI::ReceiveAIEvent(), boss_crusader_death_knightAI::ReceiveAIEvent(), boss_crusader_paladin_retriAI::ReceiveAIEvent(), npc_living_constellationAI::ReceiveAIEvent(), boss_ingvarAI::ReceiveAIEvent(), boss_crusader_druid_restoAI::ReceiveAIEvent(), boss_crusader_paladin_holyAI::ReceiveAIEvent(), boss_crusader_priest_discAI::ReceiveAIEvent(), npc_supplicantAI::ReceiveAIEvent(), npc_emilyAI::ReceiveAIEvent(), trial_companion_commonAI::ReceiveAIEvent(), npc_champion_mountAI::ReceiveAIEvent(), npc_shattered_sun_marksmanAI::ReceiveAIEvent(), npc_bt_battle_sensor::ReceiveAIEvent(), npc_headless_horseman_fireAI::ReceiveAIEvent(), npc_mojoAI::ReceiveEmote(), npc_chicken_cluckAI::ReceiveEmote(), Weather::ReGenerate(), npc_bt_battle_sensor::ReinforceAldorScryerFrontline(), Loot::Release(), Warden::RequestChallenge(), npc_kineloryAI::Reset(), npc_ironhand_guardianAI::Reset(), boss_ambassador_flamelashAI::Reset(), boss_general_angerforgeAI::Reset(), npc_rookery_hatcherAI::Reset(), boss_thermapluggAI::Reset(), boss_aranAI::Reset(), boss_bigbadwolfAI::Reset(), mob_arcane_sphereAI::Reset(), npc_a_special_surpriseAI::Reset(), boss_arcanist_doanAI::Reset(), boss_headless_horsemanAI::Reset(), boss_jandicebarovAI::Reset(), npc_spectral_tutorAI::Reset(), npc_reginald_windsorAI::Reset(), npc_shadow_imageAI::Reset(), boss_archaedasAI::Reset(), npc_taelan_fordringAI::Reset(), npc_isillienAI::Reset(), npc_tirion_fordringAI::Reset(), mob_soaring_eagleAI::Reset(), npc_soulflayerAI::Reset(), boss_mawsAI::Reset(), npc_arthasAI::Reset(), boss_aeonusAI::Reset(), boss_chrono_lord_dejaAI::Reset(), npc_doomfire_targetingAI::Reset(), npc_thrall_old_hillsbradAI::Reset(), npc_kerlonianAI::Reset(), npc_rabid_bearAI::Reset(), boss_tethyrAI::Reset(), npc_captured_arkonarinAI::Reset(), npc_areiAI::Reset(), npc_captured_sprite_darterAI::Reset(), npc_kindal_moonweaverAI::Reset(), boss_onyxiaAI::Reset(), mob_anubisath_guardianAI::Reset(), npc_solenorAI::Reset(), boss_fankrissAI::Reset(), npc_ringoAI::Reset(), npc_simone_seductressAI::Reset(), npc_simone_the_inconspicuousAI::Reset(), npc_artoriusAI::Reset(), boss_zumrahAI::Reset(), boss_amanitarAI::Reset(), boss_taldaramAI::Reset(), npc_nexus_drake_hatchlingAI::Reset(), npc_scourged_flamespitterAI::Reset(), npc_proudhoofAI::Reset(), boss_eadricAI::Reset(), boss_paletressAI::Reset(), boss_black_knightAI::Reset(), npc_black_knight_ghoulAI::Reset(), trial_companion_commonAI::Reset(), boss_champion_warriorAI::Reset(), boss_champion_mageAI::Reset(), boss_champion_hunterAI::Reset(), boss_anubarak_trialAI::Reset(), trial_crusader_commonAI::Reset(), boss_jaraxxusAI::Reset(), boss_gormokAI::Reset(), twin_jormungars_commonAI::Reset(), npc_concentrated_bulletAI::Reset(), boss_novosAI::Reset(), boss_tharonjaAI::Reset(), npc_squad_leaderAI::Reset(), npc_infantryAI::Reset(), npc_father_kamarosAI::Reset(), boss_devourer_of_soulsAI::Reset(), boss_lich_king_horAI::Reset(), blood_prince_council_baseAI::Reset(), boss_valanar_iccAI::Reset(), boss_keleseth_iccAI::Reset(), boss_taldaram_iccAI::Reset(), boss_blood_queen_lanathelAI::Reset(), boss_professor_putricideAI::Reset(), npc_volatile_ooze_iccAI::Reset(), npc_gas_cloud_iccAI::Reset(), boss_sindragosaAI::Reset(), npc_rimefang_iccAI::Reset(), npc_spinestalker_iccAI::Reset(), boss_uromAI::Reset(), boss_varosAI::Reset(), boss_sartharionAI::Reset(), boss_halion_realAI::Reset(), boss_halion_twilightAI::Reset(), boss_savianaAI::Reset(), boss_bjarngrimAI::Reset(), mob_stormforged_lieutenantAI::Reset(), boss_ionarAI::Reset(), npc_worm_holeAI::Reset(), boss_feral_defenderAI::Reset(), npc_storm_lasherAI::Reset(), boss_hodirAI::Reset(), boss_kologarnAI::Reset(), boss_vx001AI::Reset(), boss_thorimAI::Reset(), boss_sifAI::Reset(), npc_storm_tempered_keeperAI::Reset(), mob_vrykul_skeletonAI::Reset(), boss_ymironAI::Reset(), npc_decaying_ghoulAI::Reset(), boss_exarch_maladaarAI::Reset(), boss_pandemoniusAI::Reset(), boss_darkweaver_sythAI::Reset(), boss_ambassador_hellmawAI::Reset(), boss_grandmaster_vorpilAI::Reset(), boss_murmurAI::Reset(), boss_shahrazAI::Reset(), npc_bloodmaul_dire_wolfAI::Reset(), npc_apexis_flayerAI::Reset(), boss_doomlordkazzakAI::Reset(), boss_doomwalkerAI::Reset(), boss_fathomlord_karathressAI::Reset(), boss_fathomguard_caribdisAI::Reset(), npc_inner_demonAI::Reset(), boss_thespiaAI::Reset(), npc_rethhedronAI::Reset(), npc_captured_vanguardAI::Reset(), npc_saeed_escortAI::Reset(), npc_dimensiusAI::Reset(), npc_shadowlord_deathwailAI::Reset(), npc_disobedient_dragonmaw_peonAI::Reset(), npc_millhouse_manastormAI::Reset(), npc_arcatraz_defenderAI::Reset(), boss_dalliahAI::Reset(), boss_soccothratesAI::Reset(), boss_lajAI::Reset(), boss_thorngrinAI::Reset(), boss_warp_splinterAI::Reset(), boss_alarAI::Reset(), boss_thaladred_the_darkenerAI::Reset(), boss_mechano_lord_capacitusAI::Reset(), boss_nethermancer_sepethreaAI::Reset(), npc_raging_flamesAI::Reset(), boss_pathaleon_the_calculatorAI::Reset(), mob_nether_wraithAI::Reset(), npc_isla_starmaneAI::Reset(), npc_fhwoorAI::Reset(), boss_emerald_dragonAI::Reset(), npc_shade_of_the_horsemanAI::Reset(), BattleGroundDS::Reset(), Timer::ResetTimer(), WorldState::RespawnEmeraldDragons(), WorldState::RespawnHighlordKruul(), npc_lazy_peonAI::RestartWakeTimer(), Player::RewardHonor(), LootTemplate::LootGroup::Roll(), roll_chance_combat(), Unit::RollMagicResistanceMultiplierOutcomeAgainst(), Unit::RollMeleeOutcomeAgainst(), npc_corrupted_furbolgAI::SeekPurification(), Unit::SelectAttackingTarget(), Creature::SelectLevel(), boss_sifAI::SelectRandomBunnyGuid(), npc_king_ymironAI::SelectRandomCrowdNpc(), instance_obsidian_sanctum::SelectRandomFireCycloneGuid(), Unit::SelectRandomFriendlyTarget(), instance_ahnkahet::SelectRandomGuardianEggGuid(), boss_thorimAI::SelectRandomOrbGuid(), instance_zulgurub::SelectRandomPantherTrigger(), instance_gundrak::SelectRandomSladranTargetGuid(), instance_ahnkahet::SelectRandomSwarmerEggGuid(), Unit::SelectRandomUnfriendlyTarget(), boss_thorimAI::SelectRandomUpperBunny(), boss_jedogaAI::SelectRandomVolunteer(), ScriptedAI::SelectSpell(), BattleGroundSA::SendBattlegroundWarning(), boss_sartharionAI::SendFlameTsunami(), world_map_kalimdor::SetData(), instance_sunken_temple::SetData(), npc_ringoAI::SetFaint(), instance_violet_hold::SetPortalId(), npc_kerlonianAI::SetSleeping(), Creature::SetSpellList(), npc_regthar_deathgateAI::SpawnAllSlot(), npc_soulgrinderAI::SpawnCreature(), npc_regthar_deathgateAI::SpawnCreature(), instance_mount_hyjal::SpawnInfernals(), instance_mount_hyjal::SpawnOres(), world_map_outland::SpawnRandomBashirMob(), boss_kelthuzadAI::SpellHit(), boss_razuviousAI::SpellHit(), guardAI_stormwind::SpellHit(), boss_najentusAI::SpellHit(), npc_forest_frogAI::SpellHit(), mobs_nether_drakeAI::SpellHit(), npc_injured_patientAI::SpellHit(), npc_nagrand_captiveAI::SpellHitTarget(), npc_voice_yogg_saronAI::SpellHitTarget(), boss_bronjahmAI::SpellHitTarget(), boss_swamplord_muselekAI::SpellHitTarget(), boss_malacrassAI::SpellHitTarget(), npc_dragonmaw_racerAI::StartAttack(), BattlefieldWG::StartBattle(), instance_violet_hold::StartEvent(), npc_ethereum_prisonerAI::StartEvent(), WorldState::StartNewCityAttack(), WorldState::StartNewCityAttackIfTime(), npc_brewfest_barker::StartScript(), mob_blood_elf_council_voice_triggerAI::StartVoiceEvent(), boss_kelesethAI::SummonAdds(), boss_malacrassAI::SummonedCreatureJustDied(), npc_regthar_deathgateAI::SummonedCreatureJustDied(), npc_daphne_stilwellAI::SummonedCreatureJustDied(), npc_manaforge_control_consoleAI::SummonedMovementInform(), boss_jedogaAI::SummonedMovementInform(), boss_lady_vashjAI::SummonedMovementInform(), boss_warp_splinterAI::SummonTreants(), npc_lord_illidan_stormrageAI::SummonWave(), boss_gurtogg_bloodboilAI::SwitchPhase(), BattleGroundSA::TeleportPlayerToStartArea(), TerrainInfo::TerrainInfo(), Aura::TriggerSpell(), UncommonMinionspawner(), AuctionHouseBot::Update(), FormationData::Update(), instance_blackwing_lair::Update(), instance_karazhan::Update(), world_map_ebon_hold::Update(), instance_stratholme::Update(), instance_sunken_temple::Update(), instance_sunwell_plateau::Update(), instance_dark_portal::Update(), instance_zulfarrak::Update(), instance_naxxramas::Update(), instance_halls_of_stone::Update(), instance_violet_hold::Update(), instance_blood_furnace::Update(), instance_magtheridons_lair::Update(), instance_shattered_halls::Update(), instance_arcatraz::Update(), instance_pit_of_saron::Update(), instance_ulduar::Update(), instance_temple_of_ahnqiraj::Update(), AbstractRandomMovementGenerator::Update(), PetAI::UpdateAI(), guardAI::UpdateAI(), npc_ironhand_guardianAI::UpdateAI(), npc_shattered_sun_marksmanAI::UpdateAI(), mob_arcane_sphereAI::UpdateAI(), npc_forest_frogAI::UpdateAI(), npc_amanishi_tempestAI::UpdateAI(), npc_harkorAI::UpdateAI(), npc_tanzarAI::UpdateAI(), npc_krazAI::UpdateAI(), npc_ashliAI::UpdateAI(), npc_amanishi_scoutAI::UpdateAI(), npc_bonechewer_combatant::UpdateAI(), npc_disobedient_dragonmaw_peonAI::UpdateAI(), boss_thorngrinAI::UpdateAI(), boss_mechano_lord_capacitusAI::UpdateAI(), go_brewfest_music::UpdateAI(), generic_creatureAI::UpdateAI(), npc_snakesAI::UpdateAI(), npc_orphanAI::UpdateAI(), npc_shade_of_the_horsemanAI::UpdateAI(), npc_headless_horseman_fireAI::UpdateAI(), npc_scourged_flamespitterAI::UpdateAI(), boss_plugger_spazzringAI::UpdateAI(), boss_ambassador_flamelashAI::UpdateAI(), boss_emperor_dagran_thaurissanAI::UpdateAI(), boss_general_angerforgeAI::UpdateAI(), boss_overlordwyrmthalakAI::UpdateAI(), npc_rookery_hatcherAI::UpdateAI(), npc_eris_havenfireAI::UpdateAI(), npc_apprentice_mirvedaAI::UpdateAI(), boss_thermapluggAI::UpdateAI(), npc_converted_sentryAI::UpdateAI(), boss_roarAI::UpdateAI(), boss_croneAI::UpdateAI(), boss_bigbadwolfAI::UpdateAI(), boss_julianneAI::UpdateAI(), boss_romuloAI::UpdateAI(), npc_echo_of_medivhAI::UpdateAI(), npc_a_special_surpriseAI::UpdateAI(), npc_scarlet_ghoulAI::UpdateAI(), boss_arcanist_doanAI::UpdateAI(), boss_headless_horsemanAI::UpdateAI(), boss_herodAI::UpdateAI(), boss_darkmaster_gandlingAI::UpdateAI(), boss_jandicebarovAI::UpdateAI(), npc_spectral_tutorAI::UpdateAI(), boss_baroness_anastariAI::UpdateAI(), boss_cannon_master_willeyAI::UpdateAI(), boss_dathrohan_balnazzarAI::UpdateAI(), boss_maleki_the_pallidAI::UpdateAI(), mob_restless_soulAI::UpdateAI(), npc_shadow_imageAI::UpdateAI(), boss_archaedasAI::UpdateAI(), go_infernaling_summoner_portal_hound::UpdateAI(), npc_soulflayerAI::UpdateAI(), example_creatureAI::UpdateAI(), go_ai_lightning::UpdateAI(), boss_mawsAI::UpdateAI(), npc_draenei_survivorAI::UpdateAI(), boss_aeonusAI::UpdateAI(), boss_chrono_lord_dejaAI::UpdateAI(), npc_rabid_bearAI::UpdateAI(), npc_restless_apparitionAI::UpdateAI(), mob_invis_firework_helper::UpdateAI(), boss_tethyrAI::UpdateAI(), boss_onyxiaAI::UpdateAI(), npc_solenorAI::UpdateAI(), npc_simone_seductressAI::UpdateAI(), npc_simone_the_inconspicuousAI::UpdateAI(), npc_artoriusAI::UpdateAI(), boss_zumrahAI::UpdateAI(), boss_amanitarAI::UpdateAI(), boss_nadoxAI::UpdateAI(), boss_taldaramAI::UpdateAI(), boss_volazjAI::UpdateAI(), boss_anubarakAI::UpdateAI(), npc_nesingwary_trapperAI::UpdateAI(), boss_eadricAI::UpdateAI(), boss_paletressAI::UpdateAI(), boss_black_knightAI::UpdateAI(), npc_black_knight_ghoulAI::UpdateAI(), trial_companion_commonAI::UpdateAI(), npc_trial_grand_championAI::UpdateAI(), trial_crusader_commonAI::UpdateAI(), boss_jaraxxusAI::UpdateAI(), twin_jormungars_commonAI::UpdateAI(), boss_icehowlAI::UpdateAI(), boss_novosAI::UpdateAI(), boss_tharonjaAI::UpdateAI(), boss_trollgoreAI::UpdateAI(), npc_king_ymironAI::UpdateAI(), npc_infantryAI::UpdateAI(), npc_grand_admiral_westwindAI::UpdateAI(), boss_devourer_of_soulsAI::UpdateAI(), boss_lich_king_horAI::UpdateAI(), npc_blood_orb_controlAI::UpdateAI(), boss_keleseth_iccAI::UpdateAI(), boss_blood_queen_lanathelAI::UpdateAI(), boss_lord_marrowgarAI::UpdateAI(), boss_rotfaceAI::UpdateAI(), boss_sindragosaAI::UpdateAI(), npc_rimefang_iccAI::UpdateAI(), npc_spinestalker_iccAI::UpdateAI(), boss_the_lich_king_iccAI::UpdateAI(), npc_putricides_trapAI::UpdateAI(), boss_malygosAI::UpdateAI(), boss_uromAI::UpdateAI(), boss_varosAI::UpdateAI(), boss_sartharionAI::UpdateAI(), dummy_dragonAI::UpdateAI(), boss_halion_realAI::UpdateAI(), boss_halion_twilightAI::UpdateAI(), boss_savianaAI::UpdateAI(), npc_tipsy_mcmanusAI::UpdateAI(), boss_bjarngrimAI::UpdateAI(), mob_stormforged_lieutenantAI::UpdateAI(), boss_ionarAI::UpdateAI(), boss_lokenAI::UpdateAI(), boss_volkhanAI::UpdateAI(), boss_steelbreakerAI::UpdateAI(), boss_algalonAI::UpdateAI(), npc_living_constellationAI::UpdateAI(), npc_worm_holeAI::UpdateAI(), boss_feral_defenderAI::UpdateAI(), boss_flame_leviathanAI::UpdateAI(), npc_storm_lasherAI::UpdateAI(), boss_general_vezaxAI::UpdateAI(), boss_ignisAI::UpdateAI(), boss_kologarnAI::UpdateAI(), boss_mimironAI::UpdateAI(), boss_vx001AI::UpdateAI(), boss_aerial_unitAI::UpdateAI(), boss_thorimAI::UpdateAI(), boss_sifAI::UpdateAI(), npc_runic_colossusAI::UpdateAI(), boss_heart_deconstructorAI::UpdateAI(), boss_saraAI::UpdateAI(), boss_yogg_saronAI::UpdateAI(), npc_guardian_of_yoggAI::UpdateAI(), npc_immortal_guardianAI::UpdateAI(), npc_storm_tempered_keeperAI::UpdateAI(), mob_vrykul_skeletonAI::UpdateAI(), boss_ymironAI::UpdateAI(), npc_decaying_ghoulAI::UpdateAI(), boss_exarch_maladaarAI::UpdateAI(), boss_pandemoniusAI::UpdateAI(), boss_darkweaver_sythAI::UpdateAI(), boss_ambassador_hellmawAI::UpdateAI(), boss_grandmaster_vorpilAI::UpdateAI(), boss_murmurAI::UpdateAI(), mobs_nether_drakeAI::UpdateAI(), npc_bloodmaul_stout_triggerAI::UpdateAI(), npc_bloodmaul_dire_wolfAI::UpdateAI(), npc_supplicantAI::UpdateAI(), boss_doomlordkazzakAI::UpdateAI(), boss_doomwalkerAI::UpdateAI(), boss_fathomlord_karathressAI::UpdateAI(), boss_fathomguard_caribdisAI::UpdateAI(), npc_inner_demonAI::UpdateAI(), boss_thespiaAI::UpdateAI(), boss_mekgineer_steamriggerAI::UpdateAI(), boss_grand_warlock_nethekurseAI::UpdateAI(), boss_warbringer_omroggAI::UpdateAI(), boss_warchief_kargath_bladefistAI::UpdateAI(), npc_rethhedronAI::UpdateAI(), npc_saeed_escortAI::UpdateAI(), npc_dimensiusAI::UpdateAI(), mob_mature_netherwing_drakeAI::UpdateAI(), npc_shadowlord_deathwailAI::UpdateAI(), npc_spawned_oronok_tornheartAI::UpdateAI(), npc_millhouse_manastormAI::UpdateAI(), npc_arcatraz_defenderAI::UpdateAI(), boss_dalliahAI::UpdateAI(), boss_harbinger_skyrissAI::UpdateAI(), boss_soccothratesAI::UpdateAI(), boss_high_botanist_freywinnAI::UpdateAI(), boss_lajAI::UpdateAI(), boss_warp_splinterAI::UpdateAI(), boss_kaelthasAI::UpdateAI(), boss_thaladred_the_darkenerAI::UpdateAI(), boss_grand_astromancer_capernianAI::UpdateAI(), boss_master_engineer_telonicusAI::UpdateAI(), boss_nethermancer_sepethreaAI::UpdateAI(), npc_raging_flamesAI::UpdateAI(), boss_pathaleon_the_calculatorAI::UpdateAI(), mob_nether_wraithAI::UpdateAI(), go_infernaling_summoner::UpdateAI(), boss_emerald_dragonAI::UpdateAI(), npc_doctorAI::UpdateAI(), boss_champion_warriorAI::UpdateChampionAI(), boss_champion_mageAI::UpdateChampionAI(), boss_champion_shamanAI::UpdateChampionAI(), boss_champion_hunterAI::UpdateChampionAI(), boss_champion_rogueAI::UpdateCompanionAI(), mob_tenebronAI::UpdateDragonAI(), mob_shadronAI::UpdateDragonAI(), mob_vesperonAI::UpdateDragonAI(), boss_emerissAI::UpdateDragonAI(), boss_taerarAI::UpdateDragonAI(), boss_ysondreAI::UpdateDragonAI(), npc_reginald_windsorAI::UpdateEscortAI(), npc_taelan_fordringAI::UpdateEscortAI(), npc_isillienAI::UpdateEscortAI(), npc_tirion_fordringAI::UpdateEscortAI(), npc_captured_sprite_darterAI::UpdateEscortAI(), npc_keeper_remulosAI::UpdateEscortAI(), npc_kineloryAI::UpdateEscortAI(), npc_grimstoneAI::UpdateEscortAI(), npc_rizzle_sprysprocketAI::UpdateEscortAI(), npc_arthasAI::UpdateEscortAI(), npc_thrall_old_hillsbradAI::UpdateEscortAI(), npc_captured_arkonarinAI::UpdateEscortAI(), npc_areiAI::UpdateEscortAI(), npc_belnistraszAI::UpdateEscortAI(), npc_disciple_of_naralexAI::UpdateEscortAI(), npc_proudhoofAI::UpdateEscortAI(), npc_harrison_jonesAI::UpdateEscortAI(), npc_squad_leaderAI::UpdateEscortAI(), npc_father_kamarosAI::UpdateEscortAI(), npc_nagrand_captiveAI::UpdateEscortAI(), npc_captured_vanguardAI::UpdateEscortAI(), npc_akunoAI::UpdateEscortAI(), npc_isla_starmaneAI::UpdateEscortAI(), npc_fhwoorAI::UpdateEscortAI(), npc_kindal_moonweaverAI::UpdateFollowerAI(), npc_shay_leafrunnerAI::UpdateFollowerAI(), npc_nexus_drake_hatchlingAI::UpdateFollowerAI(), npc_kerlonianAI::UpdateFollowerAI(), npc_toogaAI::UpdateFollowerAI(), npc_ringoAI::UpdateFollowerAI(), CreatureEventAIHolder::UpdateRepeatTimer(), Player::UpdateSkill(), UnitAI::UpdateSpellLists(), AuctionHouseBot::ValueWithVariance(), boss_plugger_spazzringAI::WarnThief(), WindowsCodeScan::WindowsCodeScan(), WindowsDriverScan::WindowsDriverScan(), WindowsHookScan::WindowsHookScan(), and WindowsModuleScan::WindowsModuleScan().
Utf8FitTo()
bool Utf8FitTo (const std::string & str, const std::wstring & search)
Definition at line 523 of file Util.cpp.
References Utf8toWStr(), and wstrToLower().
Referenced by WorldSession::BuildListAuctionItems(), PlayerbotAI::CreatureLocalization(), PlayerbotAI::GameObjectLocalization(), PlayerbotAI::getPetSpellId(), PlayerbotAI::getSpellId(), ChatHandler::HandleLearnAllRecipesCommand(), ChatHandler::HandleLookupAchievementCommand(), ChatHandler::HandleLookupAreaCommand(), ChatHandler::HandleLookupCreatureCommand(), ChatHandler::HandleLookupEventCommand(), ChatHandler::HandleLookupFactionCommand(), ChatHandler::HandleLookupItemCommand(), ChatHandler::HandleLookupItemSetCommand(), ChatHandler::HandleLookupObjectCommand(), ChatHandler::HandleLookupQuestCommand(), ChatHandler::HandleLookupSkillCommand(), ChatHandler::HandleLookupSpellCommand(), ChatHandler::HandleLookupTaxiNodeCommand(), ChatHandler::HandleLookupTitleCommand(), WorldSession::HandleWhoOpcode(), PlayerbotAI::ItemLocalization(), and PlayerbotAI::QuestLocalization().
utf8length()
size_t utf8length (std::string & utf8str)
Definition at line 366 of file Util.cpp.
Referenced by AccountMgr::ChangePassword(), AccountMgr::ChangeUsername(), and AccountMgr::CreateAccount().
utf8limit()
size_t utf8limit (std::string & utf8str, size_t bytes)
Definition at line 380 of file Util.cpp.
Referenced by WorldSession::CheckChatChannelNameAndPassword(), WorldSession::CheckChatMessage(), GMTicket::GMTicket(), PlayerbotAI::HandleCommand(), WorldSession::HandleGMSurveySubmitOpcode(), GMTicket::Load(), GMTicket::Recycle(), WorldSession::SendGMTicketResponse(), and GMTicket::SetUpdated().
utf8printf()
void utf8printf (FILE * out, const char * str, ...)
Definition at line 536 of file Util.cpp.
References vutf8printf().
utf8ToConsole()
bool utf8ToConsole (const std::string & utf8str, std::string & conStr)
Definition at line 491 of file Util.cpp.
References Utf8toWStr().
Utf8toWStr()
bool Utf8toWStr (const std::string & utf8str, std::wstring & wstr, size_t max_len)
Definition at line 329 of file Util.cpp.
Referenced by AuctionHouseObject::AddAuction(), ObjectMgr::AddGameTele(), ObjectMgr::CheckDeclinedNames(), ObjectMgr::CheckPetName(), ObjectMgr::CheckPlayerName(), ObjectMgr::CheckPublicMessageLanguage(), AuctionEntry::CompareAuctionEntry(), ObjectMgr::DeleteGameTele(), ChannelMgr::GetChannel(), GetChatChannelsEntryFor(), ObjectMgr::GetGameTele(), ChannelMgr::GetJoinChannel(), PlayerbotAI::getPetSpellId(), PlayerbotAI::getSpellId(), WorldSession::HandleAuctionListItems(), ChatHandler::HandleLearnAllRecipesCommand(), ChatHandler::HandleLookupAchievementCommand(), ChatHandler::HandleLookupAreaCommand(), ChatHandler::HandleLookupCreatureCommand(), ChatHandler::HandleLookupEventCommand(), ChatHandler::HandleLookupFactionCommand(), ChatHandler::HandleLookupItemCommand(), ChatHandler::HandleLookupItemSetCommand(), ChatHandler::HandleLookupObjectCommand(), ChatHandler::HandleLookupQuestCommand(), ChatHandler::HandleLookupSkillCommand(), ChatHandler::HandleLookupSpellCommand(), ChatHandler::HandleLookupTaxiNodeCommand(), ChatHandler::HandleLookupTeleCommand(), ChatHandler::HandleLookupTitleCommand(), ChatHandler::HandleModifyRepCommand(), WorldSession::HandlePetRename(), WorldSession::HandleSetPlayerDeclinedNamesOpcode(), WorldSession::HandleWhoOpcode(), ObjectMgr::IsReservedName(), ObjectMgr::IsValidCharterName(), ChannelMgr::LeftChannel(), AuctionHouseMgr::LoadAuctions(), ObjectMgr::LoadGameTele(), ObjectMgr::LoadReservedPlayersNames(), normalizePlayerName(), AccountMgr::normalizeString(), NamreebAnticheat::AntispamMgr::NormalizeStringInternal(), Utf8FitTo(), utf8print(), utf8ToConsole(), utf8truncate(), and vutf8printf().
utf8truncate()
void utf8truncate (std::string & utf8str, size_t len)
Definition at line 407 of file Util.cpp.
References Utf8toWStr(), and WStrToUtf8().
Referenced by PlayerSocial::SetFriendNote(), and Guild::SetGuildBankTabText().
vutf8printf()
void vutf8printf (FILE * out, const char * str, va_list * ap)
Definition at line 544 of file Util.cpp.
References Utf8toWStr().
Referenced by Log::outBasic(), Log::outCommand(), Log::outDebug(), Log::outDetail(), Log::outError(), Log::outErrorDb(), Log::outErrorEventAI(), Log::outErrorScriptLib(), Log::outString(), and utf8printf().
WStrToUtf8()
bool WStrToUtf8 (const std::wstring & wstr, std::string & utf8str)
Definition at line 421 of file Util.cpp.
Referenced by consoleToUtf8(), normalizePlayerName(), AccountMgr::normalizeString(), and utf8truncate().
Variable Documentation
initRand
std::mt19937 * initRand static
Definition at line 35 of file Util.cpp.