CMaNGOS_WoTLK: violet_holdScripts.cpp File Reference
violet_holdScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "violet_hold.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
Data Structures
struct npc_prison_event_controllerAI
struct npc_teleportation_portalAI
struct spell_teleport_inside_violet_hold
struct spell_void_shift_aura
Enumerations
enum {
GOSSIP_ITEM_INTRO = -3608000 , GOSSIP_ITEM_START = -3608001 , GOSSIP_ITEM_TELEPORT = -3608002 , GOSSIP_TEXT_ID_INTRO = 13853 ,
GOSSIP_TEXT_ID_START = 13854 , SPELL_TELEPORT_INSIDE = 62138
}
Functions
bool EffectDummyCreature_npc_door_seal (Unit *, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
bool GossipHello_npc_sinclari (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_sinclari (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool EffectDummyCreature_npc_teleportation_portal (Unit *, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
void AddSC_violet_hold ()
Variables
static const uint32 aTrashPortalNpcs [4] = {NPC_AZURE_CAPTAIN, NPC_AZURE_RAIDER, NPC_AZURE_SORCEROR, NPC_AZURE_STALKER}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
GOSSIP_ITEM_INTRO
GOSSIP_ITEM_START
GOSSIP_ITEM_TELEPORT
GOSSIP_TEXT_ID_INTRO
GOSSIP_TEXT_ID_START
SPELL_TELEPORT_INSIDE
Definition at line 60 of file violet_holdScripts.cpp.
Function Documentation
AddSC_violet_hold()
void AddSC_violet_hold ()
Definition at line 431 of file violet_holdScripts.cpp.
References EffectDummyCreature_npc_door_seal(), EffectDummyCreature_npc_teleportation_portal(), Script::GetAI, GossipHello_npc_sinclari(), GossipSelect_npc_sinclari(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_door_seal()
bool EffectDummyCreature_npc_door_seal (Unit * , uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 41 of file violet_holdScripts.cpp.
References EFFECT_INDEX_0, WorldObject::GetInstanceData(), SPECIAL, SPELL_DESTROY_DOOR_SEAL, and TYPE_SEAL.
Referenced by AddSC_violet_hold().
EffectDummyCreature_npc_teleportation_portal()
bool EffectDummyCreature_npc_teleportation_portal (Unit * , uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 381 of file violet_holdScripts.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, EFFECT_INDEX_0, UnitAI::SendAIEvent(), and SPELL_PORTAL_PERIODIC.
Referenced by AddSC_violet_hold().
GossipHello_npc_sinclari()
bool GossipHello_npc_sinclari (Player * pPlayer, Creature * pCreature)
Definition at line 72 of file violet_holdScripts.cpp.
References WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_INTRO, GOSSIP_ITEM_TELEPORT, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID_INTRO, IN_PROGRESS, NOT_STARTED, and TYPE_MAIN.
Referenced by AddSC_violet_hold().
GossipSelect_npc_sinclari()
bool GossipSelect_npc_sinclari (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 86 of file violet_holdScripts.cpp.
References Unit::CastSpell(), WorldObject::GetInstanceData(), Unit::GetMotionMaster(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_START, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID_START, MotionMaster::MoveWaypoint(), NOT_STARTED, SPECIAL, SPELL_TELEPORT_INSIDE, TRIGGERED_OLD_TRIGGERED, and TYPE_MAIN.
Referenced by AddSC_violet_hold().
Variable Documentation
aTrashPortalNpcs
const uint32 aTrashPortalNpcs[4] = {NPC_AZURE_CAPTAIN, NPC_AZURE_RAIDER, NPC_AZURE_SORCEROR, NPC_AZURE_STALKER} static
Definition at line 239 of file violet_holdScripts.cpp.
Referenced by npc_teleportation_portalAI::DoSummon().