CMaNGOS_WoTLK: wailing_cavernsScripts.cpp File Reference
wailing_cavernsScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "wailing_caverns.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct firstWaveLocations
struct secondWaveLocations
struct thirdWaveLocations
struct npc_disciple_of_naralexAI
Enumerations
enum {
SAY_FIRST_CORNER = 1256 , SAY_CONTINUE = 1257 , SAY_CIRCLE_BANISH = 1258 , SAY_PURIFIED = 1259 ,
SAY_NARALEX_CHAMBER = 1263 , SAY_BEGIN_RITUAL = 1264 , SAY_MUTANUS = 1276 , SAY_NARALEX_AWAKE = 1271 ,
SAY_AWAKE = 2101 , SAY_NARALEX_THANKYOU = 1272 , SAY_FAREWELL = 2103 , SAY_AGGRO_1 = 1273 ,
SAY_AGGRO_2 = 1277 , SAY_AGGRO_3 = 1274 , EMOTE_RITUAL_BEGIN = 1265 , EMOTE_NARALEX_AWAKE = 1268 ,
EMOTE_BREAK_THROUGH = 1269 , EMOTE_VISION = 1270 , GOSSIP_ITEM_BEGIN = -3043000 , TEXT_ID_BEGIN = 699 ,
TEXT_ID_DISCIPLE = 698 , SPELL_MARK = 5232 , SPELL_SLEEP = 1090 , SPELL_POTION = 8141 ,
SPELL_CLEANSING = 6270 , SPELL_AWAKENING = 6271 , SPELL_SHAPESHIFT = 8153 , NPC_DEVIATE_RAPTOR = 3636 ,
NPC_DEVIATE_VIPER = 5755 , NPC_DEVIATE_ADDER = 5048 , NPC_DEVIATE_MOCCASIN = 5762 , NPC_NIGHTMARE_ECTOPLASM = 5763 ,
NPC_MUTANUS = 3654 , PATH_ID_NARALEX = 3678
}
Functions
bool GossipHello_npc_disciple_of_naralex (Player *player, Creature *creature)
bool GossipSelect_npc_disciple_of_naralex (Player *player, Creature *creature, uint32, uint32 uiAction)
void AddSC_wailing_caverns ()
Variables
static const firstWaveLocations raptorLocations [2]
static const float circleLocations [3][4]
static const secondWaveLocations moccasinLocations [3]
static const thirdWaveLocations ectoplasmLocations [7]
float mutanosLocations [4] = { 150.94276f, 262.79715f, -103.90348f, 1 }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_FIRST_CORNER
SAY_CONTINUE
SAY_CIRCLE_BANISH
SAY_PURIFIED
SAY_NARALEX_CHAMBER
SAY_BEGIN_RITUAL
SAY_MUTANUS
SAY_NARALEX_AWAKE
SAY_AWAKE
SAY_NARALEX_THANKYOU
SAY_FAREWELL
SAY_AGGRO_1
SAY_AGGRO_2
SAY_AGGRO_3
EMOTE_RITUAL_BEGIN
EMOTE_NARALEX_AWAKE
EMOTE_BREAK_THROUGH
EMOTE_VISION
GOSSIP_ITEM_BEGIN
TEXT_ID_BEGIN
TEXT_ID_DISCIPLE
SPELL_MARK
SPELL_SLEEP
SPELL_POTION
SPELL_CLEANSING
SPELL_AWAKENING
SPELL_SHAPESHIFT
NPC_DEVIATE_RAPTOR
NPC_DEVIATE_VIPER
NPC_DEVIATE_ADDER
NPC_DEVIATE_MOCCASIN
NPC_NIGHTMARE_ECTOPLASM
NPC_MUTANUS
PATH_ID_NARALEX
Definition at line 28 of file wailing_cavernsScripts.cpp.
Function Documentation
AddSC_wailing_caverns()
void AddSC_wailing_caverns ()
Definition at line 522 of file wailing_cavernsScripts.cpp.
References Script::GetAI, GossipHello_npc_disciple_of_naralex(), GossipSelect_npc_disciple_of_naralex(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
GossipHello_npc_disciple_of_naralex()
bool GossipHello_npc_disciple_of_naralex (Player * player, Creature * creature)
Definition at line 482 of file wailing_cavernsScripts.cpp.
References Unit::CastSpell(), InstanceData::GetData(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_BEGIN, GOSSIP_SENDER_MAIN, Player::IsGameMaster(), Unit::isQuestGiver(), Player::PrepareQuestMenu(), SPECIAL, SPELL_MARK, TEXT_ID_BEGIN, TEXT_ID_DISCIPLE, TRIGGERED_NONE, and TYPE_DISCIPLE.
Referenced by AddSC_wailing_caverns().
GossipSelect_npc_disciple_of_naralex()
bool GossipSelect_npc_disciple_of_naralex (Player * player, Creature * creature, uint32 , uint32 uiAction)
Definition at line 503 of file wailing_cavernsScripts.cpp.
References Creature::AI(), FACTION_ESCORT_N_NEUTRAL_ACTIVE, WorldObject::GetInstanceData(), GOSSIP_ACTION_INFO_DEF, PATH_ID_NARALEX, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_wailing_caverns().
Variable Documentation
circleLocations
const float circleLocations[3][4] static
Initial value:
=
{
    { -50.1237f, 274.7166f, -92.7608f, 3.0368f},
    { -60.2538f, 273.0981f, -92.7608f, 0.4014f},
    { -57.5452f, 280.2068f, -92.7608f, 5.0789f}
}
Definition at line 85 of file wailing_cavernsScripts.cpp.
Referenced by npc_disciple_of_naralexAI::UpdateEscortAI().
ectoplasmLocations
const thirdWaveLocations ectoplasmLocations[7] static
Initial value:
=
{
    { NPC_NIGHTMARE_ECTOPLASM, 162.06705f, 218.71494f, -105.36240f, 1},
    { NPC_NIGHTMARE_ECTOPLASM, 115.55489f, 168.22847f, -105.68655f, 2},
    { NPC_NIGHTMARE_ECTOPLASM, 82.065025f, 280.37723f, -103.29671f, 3},
    { NPC_NIGHTMARE_ECTOPLASM, 144.84305f, 278.07928f, -104.57445f, 4},
    { NPC_NIGHTMARE_ECTOPLASM, 155.84459f, 186.68817f, -107.08412f, 5},
    { NPC_NIGHTMARE_ECTOPLASM, 145.35356f, 219.34600f, -102.98572f, 6},
    { NPC_NIGHTMARE_ECTOPLASM, 164.62735f, 274.12335f, -107.29780f, 7}
}
Definition at line 114 of file wailing_cavernsScripts.cpp.
Referenced by npc_disciple_of_naralexAI::UpdateEscortAI().
moccasinLocations
const secondWaveLocations moccasinLocations[3] static
Initial value:
=
{
    { NPC_DEVIATE_MOCCASIN, 171.39545f, 213.76605f, -105.50746f, 1},
    { NPC_DEVIATE_MOCCASIN, 156.72229f, 189.91829f, -107.48995f, 2},
    { NPC_DEVIATE_MOCCASIN, 121.39977f, 166.31746f, -105.54061f, 3}
}
Definition at line 100 of file wailing_cavernsScripts.cpp.
Referenced by npc_disciple_of_naralexAI::UpdateEscortAI().
mutanosLocations
float mutanosLocations[4] = { 150.94276f, 262.79715f, -103.90348f, 1 }
Definition at line 125 of file wailing_cavernsScripts.cpp.
Referenced by npc_disciple_of_naralexAI::UpdateEscortAI().
raptorLocations
const firstWaveLocations raptorLocations[2] static
Initial value:
=
{
    { NPC_DEVIATE_RAPTOR , -67.44779f, 214.5348f, -93.42037f, 1 },
    { NPC_DEVIATE_RAPTOR , -67.85276f, 203.7873f, -93.57328f, 2 }
}
Definition at line 79 of file wailing_cavernsScripts.cpp.
Referenced by npc_disciple_of_naralexAI::UpdateEscortAI().