CMaNGOS_WoTLK: war_effort.cpp File Reference
war_effort.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "World/WorldState.h"
#include "AI/ScriptDevAI/scripts/kalimdor/world_kalimdor.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "Grids/GridNotifiers.h"
#include "Grids/GridNotifiersImpl.h"
Data Structures
class BattleGroundBroadcastBuilder
struct SilithusBossAI
Enumerations
enum Quests {
QUEST_ALLIANCE_COPPER_BARS_1 = 8492 , QUEST_ALLIANCE_COPPER_BARS_2 = 8493 , QUEST_HORDE_COPPER_BARS_1 = 8532 , QUEST_HORDE_COPPER_BARS_2 = 8533 ,
QUEST_ALLIANCE_PURPLE_LOTUS_1 = 8505 , QUEST_ALLIANCE_PURPLE_LOTUS_2 = 8506 , QUEST_HORDE_PURPLE_LOTUS_1 = 8582 , QUEST_HORDE_PURPLE_LOTUS_2 = 8583 ,
QUEST_HORDE_PEACEBLOOM_1 = 8549 , QUEST_HORDE_PEACEBLOOM_2 = 8550 , QUEST_ALLIANCE_LINEN_BANDAGE_1 = 8517 , QUEST_ALLIANCE_LINEN_BANDAGE_2 = 8518 ,
QUEST_ALLIANCE_RAINBOW_FIN_ALBACORE_1 = 8524 , QUEST_ALLIANCE_RAINBOW_FIN_ALBACORE_2 = 8525 , QUEST_ALLIANCE_LIGHT_LEATHER_1 = 8511 , QUEST_ALLIANCE_LIGHT_LEATHER_2 = 8512 ,
QUEST_HORDE_WOOL_BANDAGES_1 = 8604 , QUEST_HORDE_WOOL_BANDAGES_2 = 8605 , QUEST_ALLIANCE_STRANGLEKELP_1 = 8503 , QUEST_ALLIANCE_STRANGLEKELP_2 = 8504 ,
QUEST_ALLIANCE_MEDIUM_LEATHER_1 = 8513 , QUEST_ALLIANCE_MEDIUM_LEATHER_2 = 8514 , QUEST_HORDE_LEAN_WOLF_STEAKS_1 = 8611 , QUEST_HORDE_LEAN_WOLF_STEAKS_2 = 8612 ,
QUEST_HORDE_TIN_BARS_1 = 8542 , QUEST_HORDE_TIN_BARS_2 = 8543 , QUEST_ALLIANCE_SILK_BANDAGES_1 = 8520 , QUEST_ALLIANCE_SILK_BANDAGES_2 = 8521 ,
QUEST_ALLIANCE_IRON_BARS_1 = 8494 , QUEST_ALLIANCE_IRON_BARS_2 = 8495 , QUEST_ALLIANCE_ROAST_RAPTOR_1 = 8526 , QUEST_ALLIANCE_ROAST_RAPTOR_2 = 8527 ,
QUEST_HORDE_FIREBLOOM_1 = 8580 , QUEST_HORDE_FIREBLOOM_2 = 8581 , QUEST_HORDE_HEAVY_LEATHER_1 = 8588 , QUEST_HORDE_HEAVY_LEATHER_2 = 8589 ,
QUEST_ALLIANCE_SPOTTED_YELLOWTAIL_1 = 8528 , QUEST_ALLIANCE_SPOTTED_YELLOWTAIL_2 = 8529 , QUEST_HORDE_SPOTTED_YELLOWTAIL_1 = 8613 , QUEST_HORDE_SPOTTED_YELLOWTAIL_2 = 8614 ,
QUEST_ALLIANCE_THICK_LEATHER_1 = 8515 , QUEST_ALLIANCE_THICK_LEATHER_2 = 8516 , QUEST_HORDE_THICK_LEATHER_1 = 8590 , QUEST_HORDE_THICK_LEATHER_2 = 8591 ,
QUEST_HORDE_MITHRIL_BARS_1 = 8545 , QUEST_HORDE_MITHRIL_BARS_2 = 8546 , QUEST_ALLIANCE_RUNECLOTH_BANDAGES_1 = 8522 , QUEST_ALLIANCE_RUNECLOTH_BANDAGES_2 = 8523 ,
QUEST_HORDE_RUNECLOTH_BANDAGES_1 = 8609 , QUEST_HORDE_RUNECLOTH_BANDAGES_2 = 8610 , QUEST_ALLIANCE_ARTHAS_TEARS_1 = 8509 , QUEST_ALLIANCE_ARTHAS_TEARS_2 = 8510 ,
QUEST_ALLIANCE_THORIUM_BARS_1 = 8499 , QUEST_ALLIANCE_THORIUM_BARS_2 = 8500 , QUEST_HORDE_BAKED_SALMON_1 = 8615 , QUEST_HORDE_BAKED_SALMON_2 = 8616 ,
QUEST_HORDE_RUGGED_LEATHER_1 = 8600 , QUEST_HORDE_RUGGED_LEATHER_2 = 8601 , QUEST_HORDE_MAGEWEAVE_BANDAGE_1 = 8607 , QUEST_HORDE_MAGEWEAVE_BANDAGE_2 = 8608 ,
QUEST_BANG_A_GONG = 8743 , SAY_BANG_GONG = 11427 , SAY_QIRAJI_BREAK = 11432
}
Functions
bool QuestRewarded_war_effort (Player *player, Creature *creature, Quest const *quest)
void SendBgNeutralToPlayer (int32 bcdEntry, Unit *target)
bool QuestRewarded_war_effort (Player *player, GameObject *go, Quest const *quest)
void AddSC_war_effort ()
Enumeration Type Documentation
Quests
enum Quests
Enumerator
QUEST_ALLIANCE_COPPER_BARS_1
QUEST_ALLIANCE_COPPER_BARS_2
QUEST_HORDE_COPPER_BARS_1
QUEST_HORDE_COPPER_BARS_2
QUEST_ALLIANCE_PURPLE_LOTUS_1
QUEST_ALLIANCE_PURPLE_LOTUS_2
QUEST_HORDE_PURPLE_LOTUS_1
QUEST_HORDE_PURPLE_LOTUS_2
QUEST_HORDE_PEACEBLOOM_1
QUEST_HORDE_PEACEBLOOM_2
QUEST_ALLIANCE_LINEN_BANDAGE_1
QUEST_ALLIANCE_LINEN_BANDAGE_2
QUEST_ALLIANCE_RAINBOW_FIN_ALBACORE_1
QUEST_ALLIANCE_RAINBOW_FIN_ALBACORE_2
QUEST_ALLIANCE_LIGHT_LEATHER_1
QUEST_ALLIANCE_LIGHT_LEATHER_2
QUEST_HORDE_WOOL_BANDAGES_1
QUEST_HORDE_WOOL_BANDAGES_2
QUEST_ALLIANCE_STRANGLEKELP_1
QUEST_ALLIANCE_STRANGLEKELP_2
QUEST_ALLIANCE_MEDIUM_LEATHER_1
QUEST_ALLIANCE_MEDIUM_LEATHER_2
QUEST_HORDE_LEAN_WOLF_STEAKS_1
QUEST_HORDE_LEAN_WOLF_STEAKS_2
QUEST_HORDE_TIN_BARS_1
QUEST_HORDE_TIN_BARS_2
QUEST_ALLIANCE_SILK_BANDAGES_1
QUEST_ALLIANCE_SILK_BANDAGES_2
QUEST_ALLIANCE_IRON_BARS_1
QUEST_ALLIANCE_IRON_BARS_2
QUEST_ALLIANCE_ROAST_RAPTOR_1
QUEST_ALLIANCE_ROAST_RAPTOR_2
QUEST_HORDE_FIREBLOOM_1
QUEST_HORDE_FIREBLOOM_2
QUEST_HORDE_HEAVY_LEATHER_1
QUEST_HORDE_HEAVY_LEATHER_2
QUEST_ALLIANCE_SPOTTED_YELLOWTAIL_1
QUEST_ALLIANCE_SPOTTED_YELLOWTAIL_2
QUEST_HORDE_SPOTTED_YELLOWTAIL_1
QUEST_HORDE_SPOTTED_YELLOWTAIL_2
QUEST_ALLIANCE_THICK_LEATHER_1
QUEST_ALLIANCE_THICK_LEATHER_2
QUEST_HORDE_THICK_LEATHER_1
QUEST_HORDE_THICK_LEATHER_2
QUEST_HORDE_MITHRIL_BARS_1
QUEST_HORDE_MITHRIL_BARS_2
QUEST_ALLIANCE_RUNECLOTH_BANDAGES_1
QUEST_ALLIANCE_RUNECLOTH_BANDAGES_2
QUEST_HORDE_RUNECLOTH_BANDAGES_1
QUEST_HORDE_RUNECLOTH_BANDAGES_2
QUEST_ALLIANCE_ARTHAS_TEARS_1
QUEST_ALLIANCE_ARTHAS_TEARS_2
QUEST_ALLIANCE_THORIUM_BARS_1
QUEST_ALLIANCE_THORIUM_BARS_2
QUEST_HORDE_BAKED_SALMON_1
QUEST_HORDE_BAKED_SALMON_2
QUEST_HORDE_RUGGED_LEATHER_1
QUEST_HORDE_RUGGED_LEATHER_2
QUEST_HORDE_MAGEWEAVE_BANDAGE_1
QUEST_HORDE_MAGEWEAVE_BANDAGE_2
QUEST_BANG_A_GONG
SAY_BANG_GONG
SAY_QIRAJI_BREAK
Definition at line 24 of file war_effort.cpp.
Function Documentation
AddSC_war_effort()
void AddSC_war_effort ()
Definition at line 268 of file war_effort.cpp.
References Script::GetAI, Script::Name, Script::pQuestRewardedGO, Script::pQuestRewardedNPC, QuestRewarded_war_effort(), and Script::RegisterSelf().
Referenced by AddScripts().
QuestRewarded_war_effort() [1/2]
bool QuestRewarded_war_effort (Player * player, Creature * creature, Quest const * quest)
Definition at line 117 of file war_effort.cpp.
References AQ_ARTHAS_TEARS, AQ_BAKED_SALMON, AQ_COPPER_BAR_ALLY, AQ_COPPER_BAR_HORDE, AQ_FIREBLOOM, AQ_HEAVY_LEATHER, AQ_IRON_BAR, AQ_LEAN_WOLF_STEAK, AQ_LIGHT_LEATHER, AQ_LINEN_BANDAGE, AQ_MAGEWEAVE_BANDAGE, AQ_MEDIUM_LEATHER, AQ_MITHRIL_BAR, AQ_PEACEBLOOM, AQ_PURPLE_LOTUS_ALLY, AQ_PURPLE_LOTUS_HORDE, AQ_RAINBOW_FIN_ALBACORE, AQ_ROAST_RAPTOR, AQ_RUGGED_LEATHER, AQ_RUNECLOTH_BANDAGE_ALLY, AQ_RUNECLOTH_BANDAGE_HORDE, AQ_SILK_BANDAGE, AQ_SPOTTED_YELLOWTAIL_ALLY, AQ_SPOTTED_YELLOWTAIL_HORDE, AQ_STRANGLEKELP, AQ_THICK_LEATHER_ALLY, AQ_THICK_LEATHER_HORDE, AQ_THORIUM_BAR, AQ_TIN_BAR, AQ_WOOL_BANDAGE, Quest::GetQuestId(), QUEST_ALLIANCE_ARTHAS_TEARS_1, QUEST_ALLIANCE_ARTHAS_TEARS_2, QUEST_ALLIANCE_COPPER_BARS_1, QUEST_ALLIANCE_COPPER_BARS_2, QUEST_ALLIANCE_IRON_BARS_1, QUEST_ALLIANCE_IRON_BARS_2, QUEST_ALLIANCE_LIGHT_LEATHER_1, QUEST_ALLIANCE_LIGHT_LEATHER_2, QUEST_ALLIANCE_LINEN_BANDAGE_1, QUEST_ALLIANCE_LINEN_BANDAGE_2, QUEST_ALLIANCE_MEDIUM_LEATHER_1, QUEST_ALLIANCE_MEDIUM_LEATHER_2, QUEST_ALLIANCE_PURPLE_LOTUS_1, QUEST_ALLIANCE_PURPLE_LOTUS_2, QUEST_ALLIANCE_RAINBOW_FIN_ALBACORE_1, QUEST_ALLIANCE_RAINBOW_FIN_ALBACORE_2, QUEST_ALLIANCE_ROAST_RAPTOR_1, QUEST_ALLIANCE_ROAST_RAPTOR_2, QUEST_ALLIANCE_RUNECLOTH_BANDAGES_1, QUEST_ALLIANCE_RUNECLOTH_BANDAGES_2, QUEST_ALLIANCE_SILK_BANDAGES_1, QUEST_ALLIANCE_SILK_BANDAGES_2, QUEST_ALLIANCE_SPOTTED_YELLOWTAIL_1, QUEST_ALLIANCE_SPOTTED_YELLOWTAIL_2, QUEST_ALLIANCE_STRANGLEKELP_1, QUEST_ALLIANCE_STRANGLEKELP_2, QUEST_ALLIANCE_THICK_LEATHER_1, QUEST_ALLIANCE_THICK_LEATHER_2, QUEST_ALLIANCE_THORIUM_BARS_1, QUEST_ALLIANCE_THORIUM_BARS_2, QUEST_HORDE_BAKED_SALMON_1, QUEST_HORDE_BAKED_SALMON_2, QUEST_HORDE_COPPER_BARS_1, QUEST_HORDE_COPPER_BARS_2, QUEST_HORDE_FIREBLOOM_1, QUEST_HORDE_FIREBLOOM_2, QUEST_HORDE_HEAVY_LEATHER_1, QUEST_HORDE_HEAVY_LEATHER_2, QUEST_HORDE_LEAN_WOLF_STEAKS_1, QUEST_HORDE_LEAN_WOLF_STEAKS_2, QUEST_HORDE_MAGEWEAVE_BANDAGE_1, QUEST_HORDE_MAGEWEAVE_BANDAGE_2, QUEST_HORDE_MITHRIL_BARS_1, QUEST_HORDE_MITHRIL_BARS_2, QUEST_HORDE_PEACEBLOOM_1, QUEST_HORDE_PEACEBLOOM_2, QUEST_HORDE_PURPLE_LOTUS_1, QUEST_HORDE_PURPLE_LOTUS_2, QUEST_HORDE_RUGGED_LEATHER_1, QUEST_HORDE_RUGGED_LEATHER_2, QUEST_HORDE_RUNECLOTH_BANDAGES_1, QUEST_HORDE_RUNECLOTH_BANDAGES_2, QUEST_HORDE_SPOTTED_YELLOWTAIL_1, QUEST_HORDE_SPOTTED_YELLOWTAIL_2, QUEST_HORDE_THICK_LEATHER_1, QUEST_HORDE_THICK_LEATHER_2, QUEST_HORDE_TIN_BARS_1, QUEST_HORDE_TIN_BARS_2, QUEST_HORDE_WOOL_BANDAGES_1, QUEST_HORDE_WOOL_BANDAGES_2, Quest::ReqItemCount, and sWorldState.
Referenced by AddSC_war_effort().
QuestRewarded_war_effort() [2/2]
bool QuestRewarded_war_effort (Player * player, GameObject * go, Quest const * quest)
Definition at line 220 of file war_effort.cpp.
References WorldObject::GetInstanceData(), Quest::GetQuestId(), PHASE_3_GONG_TIME, PHASE_4_10_HOUR_WAR, QUEST_BANG_A_GONG, SAY_BANG_GONG, SAY_QIRAJI_BREAK, SendBgNeutralToPlayer(), sWorldState, and TYPE_GONG_TIME.
SendBgNeutralToPlayer()
void SendBgNeutralToPlayer (int32 bcdEntry, Unit * target)
Definition at line 210 of file war_effort.cpp.
References CHAT_MSG_BG_SYSTEM_NEUTRAL, Map::ExecuteMapWorkerZone(), WorldObject::GetMap(), sObjectMgr, and ZONE_ID_SILITHUS.
Referenced by QuestRewarded_war_effort().