CMaNGOS_WoTLK: westfall.cpp File Reference
westfall.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "AI/ScriptDevAI/base/TimerAI.h"
Data Structures
struct npc_daphne_stilwellAI
struct npc_defias_traitorAI
struct npc_foreman_klaven_mortwakeAI
Enumerations
enum {
YELL_DEFIAS_START = -1000412 , YELL_DAPHNE_START = -1000413 , SAY_DS_START = -1000293 , SAY_WAVE_DOWN_1 = -1000294 ,
SAY_WAVE_DOWN_2 = -1000295 , SAY_WAVE_DOWN_3 = -1000414 , SAY_DS_DOWN_3 = -1000296 , SAY_DS_PROLOGUE = -1000297 ,
SPELL_SHOOT = 6660 , QUEST_TOME_VALOR = 1651 , NPC_DEFIAS_RAIDER = 6180 , EQUIP_ID_RIFLE = 2511 ,
DAPHNE_SHOOT_CD = 2000
}
enum Wave { FIRST , SECOND , THIRD }
enum {
SAY_START = -1000101 , SAY_PROGRESS = -1000102 , SAY_END = -1000103 , SAY_AGGRO_1 = -1000104 ,
SAY_AGGRO_2 = -1000105 , QUEST_DEFIAS_BROTHERHOOD = 155
}
enum KlavenMortwake { SAY_STEALTH_ALERT_MORTWAKE = 3092 }
Functions
bool QuestAccept_npc_daphne_stilwell (Player *player, Creature *creature, const Quest *quest)
UnitAI * GetAI_npc_daphne_stilwell (Creature *creature)
bool QuestAccept_npc_defias_traitor (Player *player, Creature *creature, const Quest *quest)
UnitAI * GetAI_npc_defias_traitor (Creature *creature)
void AddSC_westfall ()
Variables
float RaiderCoords [15][3]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
YELL_DEFIAS_START
YELL_DAPHNE_START
SAY_DS_START
SAY_WAVE_DOWN_1
SAY_WAVE_DOWN_2
SAY_WAVE_DOWN_3
SAY_DS_DOWN_3
SAY_DS_PROLOGUE
SPELL_SHOOT
QUEST_TOME_VALOR
NPC_DEFIAS_RAIDER
EQUIP_ID_RIFLE
DAPHNE_SHOOT_CD
Definition at line 39 of file westfall.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_START
SAY_PROGRESS
SAY_END
SAY_AGGRO_1
SAY_AGGRO_2
QUEST_DEFIAS_BROTHERHOOD
Definition at line 337 of file westfall.cpp.
KlavenMortwake
enum KlavenMortwake
Enumerator
SAY_STEALTH_ALERT_MORTWAKE
Definition at line 407 of file westfall.cpp.
Wave
enum Wave
Enumerator
FIRST
SECOND
THIRD
Definition at line 58 of file westfall.cpp.
Function Documentation
AddSC_westfall()
void AddSC_westfall ()
Definition at line 427 of file westfall.cpp.
References Script::GetAI, GetAI_npc_daphne_stilwell(), GetAI_npc_defias_traitor(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_daphne_stilwell(), QuestAccept_npc_defias_traitor(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_daphne_stilwell()
UnitAI* GetAI_npc_daphne_stilwell (Creature * creature)
Definition at line 328 of file westfall.cpp.
Referenced by AddSC_westfall().
GetAI_npc_defias_traitor()
UnitAI* GetAI_npc_defias_traitor (Creature * creature)
Definition at line 398 of file westfall.cpp.
Referenced by AddSC_westfall().
QuestAccept_npc_daphne_stilwell()
bool QuestAccept_npc_daphne_stilwell (Player * player, Creature * creature, const Quest * quest)
Definition at line 315 of file westfall.cpp.
References Creature::AI(), DoScriptText(), Quest::GetQuestId(), QUEST_TOME_VALOR, and SAY_DS_START.
Referenced by AddSC_westfall().
QuestAccept_npc_defias_traitor()
bool QuestAccept_npc_defias_traitor (Player * player, Creature * creature, const Quest * quest)
Definition at line 385 of file westfall.cpp.
References Creature::AI(), DoScriptText(), Quest::GetQuestId(), QUEST_DEFIAS_BROTHERHOOD, and SAY_START.
Referenced by AddSC_westfall().
Variable Documentation
RaiderCoords
float RaiderCoords[15][3]
Initial value:
=
{
    {-11428.520f, 1612.757f, 72.241f},
    {-11422.998f, 1616.106f, 74.153f},
    {-11430.354f, 1618.334f, 72.632f},
    {-11423.307f, 1621.033f, 74.224f},
    {-11427.141f, 1623.220f, 73.168f},
    {-11453.118f, 1554.380f, 53.100f},
    {-11449.692f, 1554.672f, 53.598f},
    {-11454.533f, 1558.679f, 52.497f},
    {-11449.488f, 1557.817f, 53.443f},
    {-11452.123f, 1559.800f, 52.890f},
    {-11475.067f, 1534.259f, 50.199f},
    {-11470.306f, 1533.835f, 50.267f},
    {-11471.954f, 1539.599f, 50.273f},
    {-11465.560f, 1534.399f, 50.649f},
    {-11467.391f, 1537.989f, 50.726f}
}
Definition at line 65 of file westfall.cpp.
Referenced by npc_daphne_stilwellAI::DoSendWave(), and npc_daphne_stilwellAI::SummonedMovementInform().