CMaNGOS_WoTLK: western_plaguelands.cpp File Reference
western_plaguelands.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "Spells/Scripts/SpellScript.h"
Data Structures
struct npc_the_scourge_cauldronAI
struct npc_anchorite_truuenAI
struct npc_taelan_fordringAI
struct npc_isillienAI
struct npc_tirion_fordringAI
struct spell_placing_beacon_torch
Enumerations
enum {
SAY_BEGIN = -1000910 , SAY_FIRST_STOP = -1000911 , SAY_CONTINUE = -1000912 , SAY_FIRST_ATTACK = -1000913 ,
SAY_PURITY = -1000914 , SAY_SECOND_ATTACK = -1000915 , SAY_CLEANSE = -1000916 , SAY_WELCOME = -1000917 ,
SAY_EPILOGUE_1 = -1000918 , SAY_EPILOGUE_2 = -1000919 , NPC_PRIEST_THELDANIS = 1854 , NPC_HUNGERING_WRAITH = 1802 ,
NPC_HAUNDING_VISION = 4472 , NPC_BLIGHTED_ZOMBIE = 4475 , NPC_GHOST_OF_UTHER = 17233 , QUEST_ID_TOMB_LIGHTBRINGER = 9446
}
enum {
SAY_SCARLET_COMPLETE_1 = -1001076 , SAY_SCARLET_COMPLETE_2 = -1001077 , SAY_ESCORT_START = -1001078 , SAY_EXIT_KEEP = -1001079 ,
EMOTE_MOUNT = -1001080 , SAY_REACH_TOWER = -1001081 , SAY_ISILLIEN_1 = -1001082 , SAY_ISILLIEN_2 = -1001083 ,
SAY_ISILLIEN_3 = -1001084 , SAY_ISILLIEN_4 = -1001085 , SAY_ISILLIEN_5 = -1001086 , SAY_ISILLIEN_6 = -1001087 ,
EMOTE_ISILLIEN_ATTACK = -1001088 , SAY_ISILLIEN_ATTACK = -1001089 , SAY_KILL_TAELAN_1 = -1001090 , EMOTE_ISILLIEN_LAUGH = -1001091 ,
SAY_KILL_TAELAN_2 = -1001092 , EMOTE_ATTACK_PLAYER = -1001093 , SAY_TIRION_1 = -1001094 , SAY_TIRION_2 = -1001095 ,
SAY_TIRION_3 = -1001096 , SAY_TIRION_4 = -1001097 , SAY_TIRION_5 = -1001098 , SAY_EPILOG_1 = -1001099 ,
EMOTE_KNEEL = -1001100 , SAY_EPILOG_2 = -1001101 , EMOTE_HOLD_TAELAN = -1001102 , SAY_EPILOG_3 = -1001103 ,
SAY_EPILOG_4 = -1001104 , SAY_EPILOG_5 = -1001105 , SPELL_DEVOTION_AURA = 17232 , SPELL_CRUSADER_STRIKE = 14518 ,
SPELL_HOLY_STRIKE = 17143 , SPELL_HOLY_CLEAVE = 18819 , SPELL_HOLY_LIGHT = 15493 , SPELL_LAY_ON_HANDS = 17233 ,
SPELL_TAELAN_SUFFERING = 18810 , SPELL_DOMINATE_MIND = 14515 , SPELL_FLASH_HEAL = 10917 , SPELL_GREATER_HEAL = 10965 ,
SPELL_MANA_BURN = 15800 , SPELL_MIND_BLAST = 17194 , SPELL_MIND_FLAY = 17165 , SPELL_TAELAN_DEATH = 18969 ,
NPC_TAELAN_FORDRING = 1842 , NPC_SCARLET_CAVALIER = 1836 , NPC_ISILLIEN = 1840 , NPC_TIRION_FORDRING = 12126 ,
NPC_CRIMSON_ELITE = 12128 , MODEL_TAELAN_MOUNT = 239 , QUEST_ID_SCARLET_SUBTERFUGE = 5862 , QUEST_ID_IN_DREAMS = 5944 ,
TIRION_KNEELS_1 = 1
}
Functions
UnitAI * GetAI_npc_the_scourge_cauldron (Creature *creature)
UnitAI * GetAI_npc_anchorite_truuen (Creature *pCreature)
bool QuestAccept_npc_anchorite_truuen (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_taelan_fordring (Creature *creature)
bool QuestAccept_npc_taelan_fordring (Player *player, Creature *creature, const Quest *quest)
bool QuestRewarded_npc_taelan_fordring (Player *player, Creature *creature, const Quest *quest)
bool EffectDummyCreature_npc_taelan_fordring (Unit *caster, uint32 spellId, SpellEffectIndex effIndex, Creature *creatureTarget, ObjectGuid)
UnitAI * GetAI_npc_isillien (Creature *creature)
UnitAI * GetAI_npc_tirion_fordring (Creature *creature)
void AddSC_western_plaguelands ()
Variables
static const int32 aCavalierYells [] = { -1001072, -1001073, -1001074, -1001075 }
static const DialogueEntry aScarletDialogue []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_BEGIN
SAY_FIRST_STOP
SAY_CONTINUE
SAY_FIRST_ATTACK
SAY_PURITY
SAY_SECOND_ATTACK
SAY_CLEANSE
SAY_WELCOME
SAY_EPILOGUE_1
SAY_EPILOGUE_2
NPC_PRIEST_THELDANIS
NPC_HUNGERING_WRAITH
NPC_HAUNDING_VISION
NPC_BLIGHTED_ZOMBIE
NPC_GHOST_OF_UTHER
QUEST_ID_TOMB_LIGHTBRINGER
Definition at line 111 of file western_plaguelands.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_SCARLET_COMPLETE_1
SAY_SCARLET_COMPLETE_2
SAY_ESCORT_START
SAY_EXIT_KEEP
EMOTE_MOUNT
SAY_REACH_TOWER
SAY_ISILLIEN_1
SAY_ISILLIEN_2
SAY_ISILLIEN_3
SAY_ISILLIEN_4
SAY_ISILLIEN_5
SAY_ISILLIEN_6
EMOTE_ISILLIEN_ATTACK
SAY_ISILLIEN_ATTACK
SAY_KILL_TAELAN_1
EMOTE_ISILLIEN_LAUGH
SAY_KILL_TAELAN_2
EMOTE_ATTACK_PLAYER
SAY_TIRION_1
SAY_TIRION_2
SAY_TIRION_3
SAY_TIRION_4
SAY_TIRION_5
SAY_EPILOG_1
EMOTE_KNEEL
SAY_EPILOG_2
EMOTE_HOLD_TAELAN
SAY_EPILOG_3
SAY_EPILOG_4
SAY_EPILOG_5
SPELL_DEVOTION_AURA
SPELL_CRUSADER_STRIKE
SPELL_HOLY_STRIKE
SPELL_HOLY_CLEAVE
SPELL_HOLY_LIGHT
SPELL_LAY_ON_HANDS
SPELL_TAELAN_SUFFERING
SPELL_DOMINATE_MIND
SPELL_FLASH_HEAL
SPELL_GREATER_HEAL
SPELL_MANA_BURN
SPELL_MIND_BLAST
SPELL_MIND_FLAY
SPELL_TAELAN_DEATH
NPC_TAELAN_FORDRING
NPC_SCARLET_CAVALIER
NPC_ISILLIEN
NPC_TIRION_FORDRING
NPC_CRIMSON_ELITE
MODEL_TAELAN_MOUNT
QUEST_ID_SCARLET_SUBTERFUGE
QUEST_ID_IN_DREAMS
TIRION_KNEELS_1
Definition at line 234 of file western_plaguelands.cpp.
Function Documentation
AddSC_western_plaguelands()
void AddSC_western_plaguelands ()
Definition at line 1122 of file western_plaguelands.cpp.
References EffectDummyCreature_npc_taelan_fordring(), Script::GetAI, GetAI_npc_anchorite_truuen(), GetAI_npc_isillien(), GetAI_npc_taelan_fordring(), GetAI_npc_the_scourge_cauldron(), GetAI_npc_tirion_fordring(), Script::Name, Script::pEffectDummyNPC, Script::pQuestAcceptNPC, Script::pQuestRewardedNPC, QuestAccept_npc_anchorite_truuen(), QuestAccept_npc_taelan_fordring(), QuestRewarded_npc_taelan_fordring(), and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_taelan_fordring()
bool EffectDummyCreature_npc_taelan_fordring (Unit * caster, uint32 spellId, SpellEffectIndex effIndex, Creature * creatureTarget, ObjectGuid)
Definition at line 792 of file western_plaguelands.cpp.
References Creature::AI(), EFFECT_INDEX_0, UnitAI::EnterEvadeMode(), Object::GetEntry(), NPC_ISILLIEN, Unit::SetFacingToObject(), and SPELL_TAELAN_DEATH.
Referenced by AddSC_western_plaguelands().
GetAI_npc_anchorite_truuen()
UnitAI* GetAI_npc_anchorite_truuen (Creature * pCreature)
Definition at line 217 of file western_plaguelands.cpp.
Referenced by AddSC_western_plaguelands().
GetAI_npc_isillien()
UnitAI* GetAI_npc_isillien (Creature * creature)
Definition at line 972 of file western_plaguelands.cpp.
Referenced by AddSC_western_plaguelands().
GetAI_npc_taelan_fordring()
UnitAI* GetAI_npc_taelan_fordring (Creature * creature)
Definition at line 771 of file western_plaguelands.cpp.
Referenced by AddSC_western_plaguelands().
GetAI_npc_the_scourge_cauldron()
UnitAI* GetAI_npc_the_scourge_cauldron (Creature * creature)
Definition at line 102 of file western_plaguelands.cpp.
Referenced by AddSC_western_plaguelands().
GetAI_npc_tirion_fordring()
UnitAI* GetAI_npc_tirion_fordring (Creature * creature)
Definition at line 1101 of file western_plaguelands.cpp.
Referenced by AddSC_western_plaguelands().
QuestAccept_npc_anchorite_truuen()
bool QuestAccept_npc_anchorite_truuen (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 222 of file western_plaguelands.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ID_TOMB_LIGHTBRINGER, and UnitAI::SendAIEvent().
Referenced by AddSC_western_plaguelands().
QuestAccept_npc_taelan_fordring()
bool QuestAccept_npc_taelan_fordring (Player * player, Creature * creature, const Quest * quest)
Definition at line 776 of file western_plaguelands.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ID_IN_DREAMS, and UnitAI::SendAIEvent().
Referenced by AddSC_western_plaguelands().
QuestRewarded_npc_taelan_fordring()
bool QuestRewarded_npc_taelan_fordring (Player * player, Creature * creature, const Quest * quest)
Definition at line 784 of file western_plaguelands.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, Quest::GetQuestId(), QUEST_ID_SCARLET_SUBTERFUGE, and UnitAI::SendAIEvent().
Referenced by AddSC_western_plaguelands().
Variable Documentation
aCavalierYells
const int32 aCavalierYells[] = { -1001072, -1001073, -1001074, -1001075 } static
Definition at line 304 of file western_plaguelands.cpp.
Referenced by npc_taelan_fordringAI::JustDidDialogueStep().
aScarletDialogue
const DialogueEntry aScarletDialogue[] static
Definition at line 306 of file western_plaguelands.cpp.