CMaNGOS_WoTLK: wetlands.cpp File Reference
wetlands.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_tapoke_slim_jahnAI
Enumerations
enum {
SAY_SLIM_AGGRO = -1000977 , SAY_SLIM_DEFEAT = -1000978 , SAY_FRIEND_DEFEAT = -1000979 , SAY_SLIM_NOTES = -1000980 ,
QUEST_MISSING_DIPLOMAT11 = 1249 , FACTION_ENEMY = 168 , SPELL_STEALTH = 1785 , SPELL_CALL_FRIENDS = 16457 ,
NPC_SLIMS_FRIEND = 4971 , NPC_TAPOKE_SLIM_JAHN = 4962
}
Functions
UnitAI * GetAI_npc_tapoke_slim_jahn (Creature *pCreature)
bool QuestAccept_npc_mikhail (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AddSC_wetlands ()
Variables
static const DialogueEntry aDiplomatDialogue []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_SLIM_AGGRO
SAY_SLIM_DEFEAT
SAY_FRIEND_DEFEAT
SAY_SLIM_NOTES
QUEST_MISSING_DIPLOMAT11
FACTION_ENEMY
SPELL_STEALTH
SPELL_CALL_FRIENDS
NPC_SLIMS_FRIEND
NPC_TAPOKE_SLIM_JAHN
Definition at line 36 of file wetlands.cpp.
Function Documentation
AddSC_wetlands()
void AddSC_wetlands ()
Definition at line 227 of file wetlands.cpp.
References Script::GetAI, GetAI_npc_tapoke_slim_jahn(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_mikhail(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_tapoke_slim_jahn()
UnitAI* GetAI_npc_tapoke_slim_jahn (Creature * pCreature)
Definition at line 196 of file wetlands.cpp.
Referenced by AddSC_wetlands().
QuestAccept_npc_mikhail()
bool QuestAccept_npc_mikhail (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 205 of file wetlands.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Unit::CastSpell(), GetClosestCreatureWithEntry(), Quest::GetQuestId(), Unit::HasAura(), NPC_TAPOKE_SLIM_JAHN, QUEST_MISSING_DIPLOMAT11, UnitAI::SendAIEvent(), SPELL_STEALTH, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_wetlands().
Variable Documentation
aDiplomatDialogue
const DialogueEntry aDiplomatDialogue[] static
Initial value:
=
{
    {SAY_SLIM_DEFEAT,           NPC_TAPOKE_SLIM_JAHN,   4000},
    {SAY_SLIM_NOTES,            NPC_TAPOKE_SLIM_JAHN,   7000},
    {QUEST_MISSING_DIPLOMAT11,  0,                      0},
    {0, 0, 0},
}
Definition at line 53 of file wetlands.cpp.