CMaNGOS_WoTLK: wintergrasp.cpp File Reference
wintergrasp.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "Battlefield/BattlefieldWG.h"
#include "Spells/Scripts/SpellScript.h"
Data Structures
struct npc_spirit_guide_wintergraspAI
struct go_vehicle_teleporter
struct spell_teleport_lake_wintergrasp
struct spell_build_wintergrasp_vehicle
Enumerations
enum {
SPELL_SPIRIT_HEAL_CHANNEL = 22011 , SPELL_SPIRIT_HEAL = 22012 , SPELL_SPIRIT_HEAL_MANA = 44535 , SPELL_WAITING_TO_RESURRECT = 2584 ,
MAX_WINTERGRASP_VEHICLES = 4 , SPELL_TELEPORT_VEHICLE = 49759 , NPC_WORLD_TRIGGER = 23472
}
Functions
UnitAI * GetAI_npc_spirit_guide_wintergrasp (Creature *pCreature)
GameObjectAI * GetAI_go_vehicle_teleporter (GameObject *go)
bool ProcessEventId_event_go_tower_destroy (uint32 uiEventId, Object *pSource, Object *, bool bIsStart)
void AddSC_wintergrasp ()
Variables
static const uint32 aWintergraspVehicles [MAX_WINTERGRASP_VEHICLES] = { NPC_WINTERGRASP_CATAPULT, NPC_WINTERGRASP_DEMOLISHER, NPC_WINTERGRASP_SIEGE_ENGINE_A, NPC_WINTERGRASP_SIEGE_ENGINE_H }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_SPIRIT_HEAL_CHANNEL
SPELL_SPIRIT_HEAL
SPELL_SPIRIT_HEAL_MANA
SPELL_WAITING_TO_RESURRECT
MAX_WINTERGRASP_VEHICLES
SPELL_TELEPORT_VEHICLE
NPC_WORLD_TRIGGER
Definition at line 35 of file wintergrasp.cpp.
Function Documentation
AddSC_wintergrasp()
void AddSC_wintergrasp ()
Definition at line 281 of file wintergrasp.cpp.
References Script::GetAI, GetAI_go_vehicle_teleporter(), GetAI_npc_spirit_guide_wintergrasp(), Script::GetGameObjectAI, Script::Name, Script::pProcessEventId, ProcessEventId_event_go_tower_destroy(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_go_vehicle_teleporter()
GameObjectAI* GetAI_go_vehicle_teleporter (GameObject * go)
Definition at line 193 of file wintergrasp.cpp.
Referenced by AddSC_wintergrasp().
GetAI_npc_spirit_guide_wintergrasp()
UnitAI* GetAI_npc_spirit_guide_wintergrasp (Creature * pCreature)
Definition at line 109 of file wintergrasp.cpp.
Referenced by AddSC_wintergrasp().
ProcessEventId_event_go_tower_destroy()
bool ProcessEventId_event_go_tower_destroy (uint32 uiEventId, Object * pSource, Object * , bool bIsStart)
Definition at line 202 of file wintergrasp.cpp.
References GetCreatureListWithEntryInGrid(), Object::GetTypeId(), NPC_WINTERGRASP_TOWER_CANNON, and TYPEID_GAMEOBJECT.
Referenced by AddSC_wintergrasp().
Variable Documentation
aWintergraspVehicles
const uint32 aWintergraspVehicles[MAX_WINTERGRASP_VEHICLES] = { NPC_WINTERGRASP_CATAPULT, NPC_WINTERGRASP_DEMOLISHER, NPC_WINTERGRASP_SIEGE_ENGINE_A, NPC_WINTERGRASP_SIEGE_ENGINE_H } static
Definition at line 54 of file wintergrasp.cpp.
Referenced by go_vehicle_teleporter::UpdateAI().