CMaNGOS_WoTLK: winterspring.cpp File Reference
winterspring.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_ranshallaAI
struct npc_artoriusAI
Macros
#define GOSSIP_ITEM "Show me your real face, demon."
Enumerations
enum {
SAY_QUEST_START = -1000739 , SAY_ENTER_OWL_THICKET = -1000707 , SAY_REACH_TORCH_1 = -1000708 , SAY_REACH_TORCH_2 = -1000709 ,
SAY_REACH_TORCH_3 = -1000710 , SAY_AFTER_TORCH_1 = -1000711 , SAY_AFTER_TORCH_2 = -1000712 , SAY_REACH_ALTAR_1 = -1000713 ,
SAY_REACH_ALTAR_2 = -1000714 , SAY_RANSHALLA_ALTAR_1 = -1000715 , SAY_RANSHALLA_ALTAR_2 = -1000716 , SAY_PRIESTESS_ALTAR_3 = -1000717 ,
SAY_PRIESTESS_ALTAR_4 = -1000718 , SAY_RANSHALLA_ALTAR_5 = -1000719 , SAY_RANSHALLA_ALTAR_6 = -1000720 , SAY_PRIESTESS_ALTAR_7 = -1000721 ,
SAY_PRIESTESS_ALTAR_8 = -1000722 , SAY_PRIESTESS_ALTAR_9 = -1000723 , SAY_PRIESTESS_ALTAR_10 = -1000724 , SAY_PRIESTESS_ALTAR_11 = -1000725 ,
SAY_PRIESTESS_ALTAR_12 = -1000726 , SAY_PRIESTESS_ALTAR_13 = -1000727 , SAY_PRIESTESS_ALTAR_14 = -1000728 , SAY_VOICE_ALTAR_15 = -1000729 ,
SAY_PRIESTESS_ALTAR_16 = -1000730 , SAY_PRIESTESS_ALTAR_17 = -1000731 , SAY_PRIESTESS_ALTAR_18 = -1000732 , SAY_PRIESTESS_ALTAR_19 = -1000733 ,
SAY_PRIESTESS_ALTAR_20 = -1000734 , SAY_PRIESTESS_ALTAR_21 = -1000735 , SAY_QUEST_END_1 = -1000736 , SAY_QUEST_END_2 = -1000737 ,
EMOTE_CHANT_SPELL = -1000738 , SPELL_LIGHT_TORCH = 18953 , SPELL_RANSHALLA_DESPAWN = 18954 , SPELL_BIND_WILDKIN = 18994 ,
NPC_RANSHALLA = 10300 , NPC_PRIESTESS_ELUNE = 12116 , NPC_VOICE_ELUNE = 12152 , NPC_GUARDIAN_ELUNE = 12140 ,
NPC_PRIESTESS_DATA_1 = 1 , NPC_PRIESTESS_DATA_2 = 2 , DATA_MOVE_PRIESTESS = 3 , DATA_EVENT_END = 4 ,
GO_ELUNE_ALTAR = 177404 , GO_ELUNE_FIRE = 177417 , GO_ELUNE_GEM = 177414 , GO_ELUNE_LIGHT = 177415 ,
GO_ELUNE_AURA = 177416 , QUEST_GUARDIANS_ALTAR = 4901
}
enum {
SPELL_FOOLS_PLIGHT = 23504 , SPELL_DEMONIC_FRENZY = 23257 , SPELL_DEMONIC_DOOM = 23298 , SPELL_STINGING_TRAUMA = 23299 ,
EMOTE_POISON = -1001251 , NPC_ARTORIUS_THE_AMIABLE = 14531 , NPC_ARTORIUS_THE_DOOMBRINGER = 14535 , NPC_THE_CLEANER = 14503 ,
QUEST_STAVE_OF_THE_ANCIENTS = 7636
}
Functions
UnitAI * GetAI_npc_ranshalla (Creature *pCreature)
bool QuestAccept_npc_ranshalla (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
bool GOUse_go_elune_fire (Player *, GameObject *pGo)
bool GossipHello_npc_artorius (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_artorius (Player *pPlayer, Creature *pCreature, uint32, uint32)
UnitAI * GetAI_npc_artorius (Creature *pCreature)
void AddSC_winterspring ()
Variables
static const DialogueEntry aIntroDialogue []
static Position aWingThicketLocations []
Macro Definition Documentation
GOSSIP_ITEM
#define GOSSIP_ITEM "Show me your real face, demon."
Definition at line 503 of file winterspring.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_QUEST_START
SAY_ENTER_OWL_THICKET
SAY_REACH_TORCH_1
SAY_REACH_TORCH_2
SAY_REACH_TORCH_3
SAY_AFTER_TORCH_1
SAY_AFTER_TORCH_2
SAY_REACH_ALTAR_1
SAY_REACH_ALTAR_2
SAY_RANSHALLA_ALTAR_1
SAY_RANSHALLA_ALTAR_2
SAY_PRIESTESS_ALTAR_3
SAY_PRIESTESS_ALTAR_4
SAY_RANSHALLA_ALTAR_5
SAY_RANSHALLA_ALTAR_6
SAY_PRIESTESS_ALTAR_7
SAY_PRIESTESS_ALTAR_8
SAY_PRIESTESS_ALTAR_9
SAY_PRIESTESS_ALTAR_10
SAY_PRIESTESS_ALTAR_11
SAY_PRIESTESS_ALTAR_12
SAY_PRIESTESS_ALTAR_13
SAY_PRIESTESS_ALTAR_14
SAY_VOICE_ALTAR_15
SAY_PRIESTESS_ALTAR_16
SAY_PRIESTESS_ALTAR_17
SAY_PRIESTESS_ALTAR_18
SAY_PRIESTESS_ALTAR_19
SAY_PRIESTESS_ALTAR_20
SAY_PRIESTESS_ALTAR_21
SAY_QUEST_END_1
SAY_QUEST_END_2
EMOTE_CHANT_SPELL
SPELL_LIGHT_TORCH
SPELL_RANSHALLA_DESPAWN
SPELL_BIND_WILDKIN
NPC_RANSHALLA
NPC_PRIESTESS_ELUNE
NPC_VOICE_ELUNE
NPC_GUARDIAN_ELUNE
NPC_PRIESTESS_DATA_1
NPC_PRIESTESS_DATA_2
DATA_MOVE_PRIESTESS
DATA_EVENT_END
GO_ELUNE_ALTAR
GO_ELUNE_FIRE
GO_ELUNE_GEM
GO_ELUNE_LIGHT
GO_ELUNE_AURA
QUEST_GUARDIANS_ALTAR
Definition at line 35 of file winterspring.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_FOOLS_PLIGHT
SPELL_DEMONIC_FRENZY
SPELL_DEMONIC_DOOM
SPELL_STINGING_TRAUMA
EMOTE_POISON
NPC_ARTORIUS_THE_AMIABLE
NPC_ARTORIUS_THE_DOOMBRINGER
NPC_THE_CLEANER
QUEST_STAVE_OF_THE_ANCIENTS
Definition at line 486 of file winterspring.cpp.
Function Documentation
AddSC_winterspring()
void AddSC_winterspring ()
Definition at line 721 of file winterspring.cpp.
References Script::GetAI, GetAI_npc_artorius(), GetAI_npc_ranshalla(), GossipHello_npc_artorius(), GossipSelect_npc_artorius(), GOUse_go_elune_fire(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pGOUse, Script::pQuestAcceptNPC, QuestAccept_npc_ranshalla(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_artorius()
UnitAI* GetAI_npc_artorius (Creature * pCreature)
Definition at line 716 of file winterspring.cpp.
Referenced by AddSC_winterspring().
GetAI_npc_ranshalla()
UnitAI* GetAI_npc_ranshalla (Creature * pCreature)
Definition at line 448 of file winterspring.cpp.
Referenced by AddSC_winterspring().
GossipHello_npc_artorius()
bool GossipHello_npc_artorius (Player * pPlayer, Creature * pCreature)
Definition at line 700 of file winterspring.cpp.
References Player::GetGossipTextId(), Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ITEM, GOSSIP_SENDER_MAIN, QUEST_STATUS_INCOMPLETE, and QUEST_STAVE_OF_THE_ANCIENTS.
Referenced by AddSC_winterspring().
GossipSelect_npc_artorius()
bool GossipSelect_npc_artorius (Player * pPlayer, Creature * pCreature, uint32 , uint32)
Definition at line 709 of file winterspring.cpp.
References Creature::AI(), and Object::GetObjectGuid().
Referenced by AddSC_winterspring().
GOUse_go_elune_fire()
bool GOUse_go_elune_fire (Player * , GameObject * pGo)
Definition at line 469 of file winterspring.cpp.
References GetClosestCreatureWithEntry(), Object::GetEntry(), GO_ELUNE_ALTAR, and NPC_RANSHALLA.
Referenced by AddSC_winterspring().
QuestAccept_npc_ranshalla()
bool QuestAccept_npc_ranshalla (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 453 of file winterspring.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_A_NEUTRAL_PASSIVE, Quest::GetQuestId(), QUEST_GUARDIANS_ALTAR, SAY_QUEST_START, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_winterspring().
Variable Documentation
aIntroDialogue
const DialogueEntry aIntroDialogue[] static
Definition at line 98 of file winterspring.cpp.
aWingThicketLocations
Position aWingThicketLocations[] static
Initial value:
=
{
    {5515.98f, -4903.43f, 846.30f, 4.58f},
    {5501.94f, -4920.20f, 848.69f, 6.15f},
    {5497.35f, -4906.49f, 850.83f, 2.76f},
    {5518.38f, -4913.47f, 845.57f},
    {5510.36f, -4921.17f, 846.33f},
    {5511.31f, -4913.82f, 847.17f},
    {5518.51f, -4917.56f, 845.23f},
    {5514.40f, -4921.16f, 845.49f}
}
Definition at line 132 of file winterspring.cpp.
Referenced by npc_ranshallaAI::DoSummonPriestess(), and npc_ranshallaAI::JustDidDialogueStep().