CMaNGOS_WoTLK: world_map_scripts.cpp File Reference
world_map_scripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "world_map_scripts.h"
#include "World/WorldState.h"
#include "World/WorldStateDefines.h"
#include "Entities/TemporarySpawn.h"
#include <array>
#include <ctime>
#include <cstring>
#include "AI/ScriptDevAI/scripts/world/scourge_invasion.h"
#include "World/World.h"
#include "brewfest.h"
Enumerations
enum {
SAY_DUROTAR_FROM_OG_ARRIVAL = -1020001 , SAY_TIRISFAL_FROM_UC_ARRIVAL = -1020002 , SAY_ST_FROM_GROMGOL_ARRIVAL = -1020003 , SAY_WK_DEPARTURE = -1020004 ,
SAY_WK_ARRIVAL = -1020005 , SAY_UC_FROM_VL_ARRIVAL = -1020006 , SAY_OG_FROM_BT_ARRIVAL = -1020007 , SAY_OG_FROM_TB_ARRIVAL = -1020008 ,
EVENT_UC_FROM_GROMGOL_ARRIVAL = 15312 , EVENT_GROMGOL_FROM_UC_ARRIVAL = 15314 , EVENT_OG_FROM_UC_ARRIVAL = 15318 , EVENT_UC_FROM_OG_ARRIVAL = 15320 ,
EVENT_OG_FROM_GROMGOL_ARRIVAL = 15322 , EVENT_GROMGOL_FROM_OG_ARRIVAL = 15324 , EVENT_WK_DEPARTURE = 15430 , EVENT_WK_ARRIVAL = 15431 ,
EVENT_VL_FROM_UC_ARRIVAL = 19126 , EVENT_UC_FROM_VL_ARRIVAL = 19127 , EVENT_OG_FROM_BT_ARRIVAL = 19137 , EVENT_BT_FROM_OG_ARRIVAL = 19139 ,
EVENT_OG_FROM_TB_ARRIVAL = 21868 , EVENT_TB_FROM_OG_ARRIVAL = 21870 , RELAY_UC_FROM_GROMGOL_ARRIVAL = 21000 , RELAY_GROMGOL_FROM_UC_ARRIVAL = 21001 ,
RELAY_OG_FROM_UC_ARRIVAL = 21002 , RELAY_UC_FROM_OG_ARRIVAL = 21003 , RELAY_OG_FROM_GROMGOL_ARRIVAL = 21004 , RELAY_GROMGOL_FROM_OG_ARRIVAL = 21005 ,
RELAY_VL_FROM_UC_ARRIVAL = 21006 , RELAY_UC_FROM_VL_ARRIVAL = 21007 , RELAY_OG_FROM_BT_ARRIVAL = 21008 , RELAY_BT_FROM_OG_ARRIVAL = 21009 ,
RELAY_OG_FROM_TB_ARRIVAL = 21010 , RELAY_TB_FROM_OG_ARRIVAL = 21011 , SOUND_ZEPPELIN_HORN = 11804
}
Functions
bool ProcessEventTransports (uint32 uiEventId, Object *pSource, Object *, bool)
void AddSC_world_map_scripts ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_DUROTAR_FROM_OG_ARRIVAL
SAY_TIRISFAL_FROM_UC_ARRIVAL
SAY_ST_FROM_GROMGOL_ARRIVAL
SAY_WK_DEPARTURE
SAY_WK_ARRIVAL
SAY_UC_FROM_VL_ARRIVAL
SAY_OG_FROM_BT_ARRIVAL
SAY_OG_FROM_TB_ARRIVAL
EVENT_UC_FROM_GROMGOL_ARRIVAL
EVENT_GROMGOL_FROM_UC_ARRIVAL
EVENT_OG_FROM_UC_ARRIVAL
EVENT_UC_FROM_OG_ARRIVAL
EVENT_OG_FROM_GROMGOL_ARRIVAL
EVENT_GROMGOL_FROM_OG_ARRIVAL
EVENT_WK_DEPARTURE
EVENT_WK_ARRIVAL
EVENT_VL_FROM_UC_ARRIVAL
EVENT_UC_FROM_VL_ARRIVAL
EVENT_OG_FROM_BT_ARRIVAL
EVENT_BT_FROM_OG_ARRIVAL
EVENT_OG_FROM_TB_ARRIVAL
EVENT_TB_FROM_OG_ARRIVAL
RELAY_UC_FROM_GROMGOL_ARRIVAL
RELAY_GROMGOL_FROM_UC_ARRIVAL
RELAY_OG_FROM_UC_ARRIVAL
RELAY_UC_FROM_OG_ARRIVAL
RELAY_OG_FROM_GROMGOL_ARRIVAL
RELAY_GROMGOL_FROM_OG_ARRIVAL
RELAY_VL_FROM_UC_ARRIVAL
RELAY_UC_FROM_VL_ARRIVAL
RELAY_OG_FROM_BT_ARRIVAL
RELAY_BT_FROM_OG_ARRIVAL
RELAY_OG_FROM_TB_ARRIVAL
RELAY_TB_FROM_OG_ARRIVAL
SOUND_ZEPPELIN_HORN
Definition at line 36 of file world_map_scripts.cpp.
Function Documentation
AddSC_world_map_scripts()
void AddSC_world_map_scripts ()
Definition at line 264 of file world_map_scripts.cpp.
References Script::Name, Script::pProcessEventId, ProcessEventTransports(), and Script::RegisterSelf().
Referenced by AddScripts().
ProcessEventTransports()
bool ProcessEventTransports (uint32 uiEventId, Object * pSource, Object * , bool)
Definition at line 78 of file world_map_scripts.cpp.
References DoScriptText(), EVENT_BT_FROM_OG_ARRIVAL, EVENT_GROMGOL_FROM_OG_ARRIVAL, EVENT_GROMGOL_FROM_UC_ARRIVAL, EVENT_OG_FROM_BT_ARRIVAL, EVENT_OG_FROM_GROMGOL_ARRIVAL, EVENT_OG_FROM_TB_ARRIVAL, EVENT_OG_FROM_UC_ARRIVAL, EVENT_TB_FROM_OG_ARRIVAL, EVENT_UC_FROM_GROMGOL_ARRIVAL, EVENT_UC_FROM_OG_ARRIVAL, EVENT_UC_FROM_VL_ARRIVAL, EVENT_VL_FROM_UC_ARRIVAL, EVENT_WK_ARRIVAL, EVENT_WK_DEPARTURE, Object::GetEntry(), Map::GetInstanceData(), WorldObject::GetMap(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_DRENK_SPANNERSPARK, NPC_FREZZA, NPC_GREEB_RAMROCKET, NPC_HARROWMEISER, NPC_HINDENBURG, NPC_KRENDLE_BIGPOCKETS, NPC_MEEFI_FARTHROTTLE, NPC_NARGO_SCREWBORE, NPC_NEZRAZ, NPC_SNURK_BUCKSQUICK, NPC_SQUIBBY_OVERSPECK, NPC_ZAPETTA, NPC_ZELLI_HOTNOZZLE, RELAY_BT_FROM_OG_ARRIVAL, RELAY_GROMGOL_FROM_OG_ARRIVAL, RELAY_GROMGOL_FROM_UC_ARRIVAL, RELAY_OG_FROM_BT_ARRIVAL, RELAY_OG_FROM_GROMGOL_ARRIVAL, RELAY_OG_FROM_TB_ARRIVAL, RELAY_OG_FROM_UC_ARRIVAL, RELAY_TB_FROM_OG_ARRIVAL, RELAY_UC_FROM_GROMGOL_ARRIVAL, RELAY_UC_FROM_OG_ARRIVAL, RELAY_UC_FROM_VL_ARRIVAL, RELAY_VL_FROM_UC_ARRIVAL, SAY_DUROTAR_FROM_OG_ARRIVAL, SAY_OG_FROM_BT_ARRIVAL, SAY_OG_FROM_TB_ARRIVAL, SAY_ST_FROM_GROMGOL_ARRIVAL, SAY_TIRISFAL_FROM_UC_ARRIVAL, SAY_UC_FROM_VL_ARRIVAL, SAY_WK_ARRIVAL, SAY_WK_DEPARTURE, SCRIPT_TYPE_RELAY, SOUND_ZEPPELIN_HORN, and sWorldState.
Referenced by AddSC_world_map_scripts().