CMaNGOS_WoTLK: WorldSession.cpp File Reference
WorldSession.cpp File Reference
User to World Communication
#include <zlib.h>
#include "Server/WorldSocket.h"
#include "Common.h"
#include "Database/DatabaseEnv.h"
#include "Log.h"
#include "Server/Opcodes.h"
#include "Server/WorldPacket.h"
#include "Server/WorldSession.h"
#include "Entities/Player.h"
#include "Globals/ObjectMgr.h"
#include "Groups/Group.h"
#include "Guilds/Guild.h"
#include "Guilds/GuildMgr.h"
#include "World/World.h"
#include "BattleGround/BattleGroundMgr.h"
#include "Social/SocialMgr.h"
#include "Auth/HMACSHA1.h"
#include "GMTickets/GMTicketMgr.h"
#include "Loot/LootMgr.h"
#include "Anticheat/Anticheat.hpp"
#include <boost/asio/ip/address_v4.hpp>
#include <mutex>
#include <deque>
#include <cstdarg>
#include <iostream>
Functions
static bool MapSessionFilterHelper (WorldSession *session, OpcodeHandler const &opHandle)
Function Documentation
MapSessionFilterHelper()
static bool MapSessionFilterHelper (WorldSession * session, OpcodeHandler const & opHandle) static
Definition at line 58 of file WorldSession.cpp.
References WorldSession::GetPlayer(), Object::IsInWorld(), OpcodeHandler::packetProcessing, and PROCESS_THREADUNSAFE.
Referenced by MapSessionFilter::Process(), and WorldSessionFilter::Process().