CMaNGOS_WoTLK: WorldStateExpression.cpp File Reference
WorldStateExpression.cpp File Reference
#include "WorldStateExpression.h"
#include "Entities/Player.h"
#include "GameEvents/GameEventMgr.h"
#include "Globals/Conditions.h"
#include "Globals/ObjectMgr.h"
#include <string_view>
Functions
void HexStrToByteArray (std::string_view str, uint8 *out, size_t outlen, bool reverse)
ByteBuffer HexToBytes (const std::string &hex)
int32 EvalSingleValue (ByteBuffer &buffer, Map const *map)
int32 EvalValue (ByteBuffer &buffer, Map const *map)
bool EvalRelOp (ByteBuffer &buffer, Map const *map)
Variables
static int32(*const WorldStateExpressionFunctions [WSE_FUNCTION_MAX])(Map const *, uint32, uint32)
Function Documentation
EvalRelOp()
bool EvalRelOp (ByteBuffer & buffer, Map const * map)
Definition at line 372 of file WorldStateExpression.cpp.
References ConditionEntry::CheckOp(), EvalValue(), NONE, and ByteBuffer::read().
Referenced by WorldStateExpressionMgr::Meets().
EvalSingleValue()
int32 EvalSingleValue (ByteBuffer & buffer, Map const * map)
Definition at line 311 of file WorldStateExpression.cpp.
References CONSTANT, FUNCTION, WorldStateVariableManager::GetVariable(), Map::GetVariableManager(), ByteBuffer::read(), WORLDSTATE, and WSE_FUNCTION_MAX.
Referenced by EvalValue().
EvalValue()
int32 EvalValue (ByteBuffer & buffer, Map const * map)
Definition at line 348 of file WorldStateExpression.cpp.
References DIVISION, EvalSingleValue(), MULTIPLICATION, NONE, ByteBuffer::read(), REMAINDER, SUBTRACTION, and SUM.
Referenced by EvalRelOp().
HexStrToByteArray()
void HexStrToByteArray (std::string_view str, uint8 * out, size_t outlen, bool reverse)
Definition at line 27 of file WorldStateExpression.cpp.
References MANGOS_ASSERT.
Referenced by HexToBytes().
HexToBytes()
ByteBuffer HexToBytes (const std::string & hex)
Definition at line 50 of file WorldStateExpression.cpp.
References ByteBuffer::contents(), HexStrToByteArray(), and ByteBuffer::size().
Referenced by WorldStateExpressionMgr::Meets().
Variable Documentation
WorldStateExpressionFunctions
int32(* const WorldStateExpressionFunctions[WSE_FUNCTION_MAX])(Map const *, uint32, uint32) (Map const * , uint32 , uint32) static
Definition at line 57 of file WorldStateExpression.cpp.