CMaNGOS_WoTLK: world_eastern_kingdoms.cpp File Reference
world_eastern_kingdoms.cpp File Reference
#include "world_eastern_kingdoms.h"
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/scripts/world/world_map_scripts.h"
#include "AI/ScriptDevAI/base/TimerAI.h"
#include "World/WorldState.h"
#include "World/WorldStateDefines.h"
#include "GameEvents/GameEventMgr.h"
#include "AI/ScriptDevAI/scripts/world/brewfest.h"
#include "AI/ScriptDevAI/scripts/world/scourge_invasion.h"
Data Structures
struct world_map_eastern_kingdoms
struct go_infernaling_summoner_portal_hound
struct npc_agent_proudwell
Functions
GameObjectAI * GetAI_go_infernaling_summoner_portal_hound (GameObject *go)
bool GOUse_go_infernaling_summoner_portal_hound (Player *, GameObject *pGo)
UnitAI * GetAI_npc_agent_proudwell (Creature *pCreature)
InstanceData * GetInstanceData_world_map_eastern_kingdoms (Map *pMap)
void AddSC_world_eastern_kingdoms ()
Function Documentation
AddSC_world_eastern_kingdoms()
void AddSC_world_eastern_kingdoms ()
Definition at line 476 of file world_eastern_kingdoms.cpp.
References Script::GetAI, GetAI_go_infernaling_summoner_portal_hound(), GetAI_npc_agent_proudwell(), Script::GetGameObjectAI, Script::GetInstanceData, GetInstanceData_world_map_eastern_kingdoms(), GOUse_go_infernaling_summoner_portal_hound(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_go_infernaling_summoner_portal_hound()
GameObjectAI* GetAI_go_infernaling_summoner_portal_hound (GameObject * go)
Definition at line 419 of file world_eastern_kingdoms.cpp.
Referenced by AddSC_world_eastern_kingdoms().
GetAI_npc_agent_proudwell()
UnitAI* GetAI_npc_agent_proudwell (Creature * pCreature)
Definition at line 466 of file world_eastern_kingdoms.cpp.
Referenced by AddSC_world_eastern_kingdoms().
GetInstanceData_world_map_eastern_kingdoms()
InstanceData* GetInstanceData_world_map_eastern_kingdoms (Map * pMap)
Definition at line 471 of file world_eastern_kingdoms.cpp.
Referenced by AddSC_world_eastern_kingdoms().
GOUse_go_infernaling_summoner_portal_hound()
bool GOUse_go_infernaling_summoner_portal_hound (Player * , GameObject * pGo)
Definition at line 425 of file world_eastern_kingdoms.cpp.
References WorldObject::GetInstanceData(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_AGENT_PROUDWELL, SPELL_SUMMON_INFERNALING_PORTAL_HOUND, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_world_eastern_kingdoms().