CMaNGOS_WoTLK: zangarmarsh.cpp File Reference
zangarmarsh.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "Maps/MapManager.h"
Data Structures
struct npc_cooshcooshAI
struct npc_kayra_longmaneAI
struct StormcrowAmulet
struct npc_fhwoorAI
struct npc_frostbiteAI
Enumerations
enum { SPELL_LIGHTNING_BOLT = 9532 }
enum {
SAY_START = -1001243 , SAY_AMBUSH1 = -1001244 , SAY_PROGRESS1 = -1001245 , SAY_AMBUSH2 = -1001246 ,
SAY_PROGRESS2 = -1001247 , SAY_END = -1001248 , SAY_SLAVEBINDER_AMBUSH2 = -1001249 , QUEST_ESCAPE_FROM = 9752 ,
NPC_SLAVEBINDER = 18042
}
enum {
EVENT_ID_STORMCROW = 11225 , RELAY_SCRIPT_CROW_FLIES = 10205 , MODEL_ID_CROW = 17447 , MODEL_ID_INVISIBLE = 17657 ,
NPC_YSIEL_WINDSINGER = 17841
}
enum {
SAY_ESCORT_START = -1000995 , SAY_PREPARE = -1000996 , SAY_CAMP_ENTER = -1000997 , SAY_AMBUSH = -1000998 ,
SAY_AMBUSH_CLEARED = -1000999 , SAY_ESCORT_COMPLETE = -1001000 , SPELL_STOMP = 31277 , SPELL_THUNDERSHOCK = 31964 ,
NPC_ENCHANTRESS = 18088 , NPC_SLAVEDRIVER = 18089 , NPC_SSSLITH = 18154 , GO_ARK_OF_SSSLITH = 182082 ,
QUEST_ID_FHWOOR_SMASH = 9729
}
enum {
SPELL_FROSTBITE_ROTATE = 34748 , SPELL_PERIODIC_TRIGGER_DUMMY = 30023 , SPELL_FROST_RING_FRONT = 34740 , SPELL_FROST_RING_BEHIND = 34746 ,
SPELL_FREEZING_CIRCLE = 34779
}
Functions
UnitAI * GetAI_npc_cooshcoosh (Creature *pCreature)
bool QuestAccept_npc_kayra_longmane (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_kayra_longmane (Creature *pCreature)
bool ProcessEventId_event_taxi_stormcrow (uint32 uiEventId, Object *pSource, Object *, bool bIsStart)
UnitAI * GetAI_npc_fhwoor (Creature *pCreature)
bool QuestAccept_npc_fhwoor (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_frostbite (Creature *creature)
void AddSC_zangarmarsh ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_LIGHTNING_BOLT
Definition at line 39 of file zangarmarsh.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_START
SAY_AMBUSH1
SAY_PROGRESS1
SAY_AMBUSH2
SAY_PROGRESS2
SAY_END
SAY_SLAVEBINDER_AMBUSH2
QUEST_ESCAPE_FROM
NPC_SLAVEBINDER
Definition at line 88 of file zangarmarsh.cpp.
anonymous enum
anonymous enum
Enumerator
EVENT_ID_STORMCROW
RELAY_SCRIPT_CROW_FLIES
MODEL_ID_CROW
MODEL_ID_INVISIBLE
NPC_YSIEL_WINDSINGER
Definition at line 178 of file zangarmarsh.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_ESCORT_START
SAY_PREPARE
SAY_CAMP_ENTER
SAY_AMBUSH
SAY_AMBUSH_CLEARED
SAY_ESCORT_COMPLETE
SPELL_STOMP
SPELL_THUNDERSHOCK
NPC_ENCHANTRESS
NPC_SLAVEDRIVER
NPC_SSSLITH
GO_ARK_OF_SSSLITH
QUEST_ID_FHWOOR_SMASH
Definition at line 227 of file zangarmarsh.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_FROSTBITE_ROTATE
SPELL_PERIODIC_TRIGGER_DUMMY
SPELL_FROST_RING_FRONT
SPELL_FROST_RING_BEHIND
SPELL_FREEZING_CIRCLE
Definition at line 381 of file zangarmarsh.cpp.
Function Documentation
AddSC_zangarmarsh()
void AddSC_zangarmarsh ()
Definition at line 454 of file zangarmarsh.cpp.
References Script::GetAI, GetAI_npc_cooshcoosh(), GetAI_npc_fhwoor(), GetAI_npc_frostbite(), GetAI_npc_kayra_longmane(), Script::Name, Script::pProcessEventId, Script::pQuestAcceptNPC, ProcessEventId_event_taxi_stormcrow(), QuestAccept_npc_fhwoor(), QuestAccept_npc_kayra_longmane(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_cooshcoosh()
UnitAI* GetAI_npc_cooshcoosh (Creature * pCreature)
Definition at line 79 of file zangarmarsh.cpp.
Referenced by AddSC_zangarmarsh().
GetAI_npc_fhwoor()
UnitAI* GetAI_npc_fhwoor (Creature * pCreature)
Definition at line 361 of file zangarmarsh.cpp.
Referenced by AddSC_zangarmarsh().
GetAI_npc_frostbite()
UnitAI* GetAI_npc_frostbite (Creature * creature)
Definition at line 449 of file zangarmarsh.cpp.
Referenced by AddSC_zangarmarsh().
GetAI_npc_kayra_longmane()
UnitAI* GetAI_npc_kayra_longmane (Creature * pCreature)
Definition at line 169 of file zangarmarsh.cpp.
Referenced by AddSC_zangarmarsh().
ProcessEventId_event_taxi_stormcrow()
bool ProcessEventId_event_taxi_stormcrow (uint32 uiEventId, Object * pSource, Object * , bool bIsStart)
Definition at line 187 of file zangarmarsh.cpp.
References EVENT_ID_STORMCROW, Object::GetTypeId(), and TYPEID_PLAYER.
Referenced by AddSC_zangarmarsh().
QuestAccept_npc_fhwoor()
bool QuestAccept_npc_fhwoor (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 366 of file zangarmarsh.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ID_FHWOOR_SMASH, and UnitAI::SendAIEvent().
Referenced by AddSC_zangarmarsh().
QuestAccept_npc_kayra_longmane()
bool QuestAccept_npc_kayra_longmane (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 156 of file zangarmarsh.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_N_FRIEND_ACTIVE, Quest::GetQuestId(), QUEST_ESCAPE_FROM, SAY_START, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_zangarmarsh().