CMaNGOS_WoTLK: zulamanScripts.cpp File Reference
zulamanScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "zulaman.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_forest_frogAI
struct npc_harrison_jones_zaAI
struct npc_amanishi_lookoutAI
struct npc_amanishi_tempestAI
struct npc_harkorAI
struct npc_tanzarAI
struct npc_krazAI
struct npc_ashliAI
struct npc_amanishi_scoutAI
struct CallOfTheBeast
struct npc_eagle_trash_aggro_triggerAI
Enumerations
enum {
SPELL_REMOVE_AMANI_CURSE = 43732 , SPELL_PUSH_MOJO = 43923 , SPELL_SUMMON_AMANI_CHARM_1 = 43756 , SPELL_SUMMON_AMANI_CHARM_2 = 43824 ,
SPELL_SUMMON_AMANI_CHARM_3 = 43825 , SPELL_SUMMON_AMANI_CHARM_4 = 43826 , SPELL_SUMMON_AMANI_CHARM_5 = 43835 , SPELL_SUMMON_MONEY_BAG = 43774 ,
SPELL_STEALTH = 34189 , NPC_FOREST_FROG = 24396 , NPC_MANNUTH = 24397 , NPC_DEEZ = 24403 ,
NPC_GALATHRYN = 24404 , NPC_ADARRAH = 24405 , NPC_FUDGERICK = 24406 , NPC_DARWEN = 24407 ,
NPC_GUNTER = 24408 , NPC_KYREN = 24409 , NPC_MITZI = 24445 , NPC_CHRISTIAN = 24448 ,
NPC_BRENNAN = 24453 , NPC_HOLLEE = 24455 , SAY_MANNUTH_1 = -1568122 , SAY_MANNUTH_2 = -1568123 ,
SAY_MANNUTH_3 = -1568124 , SAY_MANNUTH_4 = -1568125 , SAY_DEEZ_1 = -1568126 , SAY_DEEZ_2 = -1568127 ,
SAY_DEEZ_3 = -1568128 , SAY_DEEZ_4 = -1568129 , SAY_GALATHRYN_1 = -1568130 , SAY_GALATHRYN_2 = -1568131 ,
SAY_GALATHRYN_3 = -1568132 , SAY_GALATHRYN_4 = -1568133 , SAY_ADARRAH_1 = -1568134 , SAY_ADARRAH_2 = -1568135 ,
SAY_ADARRAH_3 = -1568136 , SAY_ADARRAH_4 = -1568137 , SAY_DARWEN_1 = -1568138 , SAY_DARWEN_2 = -1568139 ,
SAY_DARWEN_3 = -1568140 , SAY_DARWEN_4 = -1568141 , SAY_FUDGERICK_1 = -1568142 , SAY_FUDGERICK_2 = -1568143 ,
SAY_FUDGERICK_3 = -1568144 , SAY_FUDGERICK_4 = -1568145 , SAY_GUNTER_1 = -1568146 , SAY_GUNTER_2 = -1568147 ,
SAY_GUNTER_3 = -1568148 , SAY_GUNTER_4 = -1568149 , SAY_KYREN_1 = -1568150 , SAY_KYREN_2 = -1568151 ,
SAY_KYREN_3 = -1568152 , SAY_KYREN_4 = -1568153 , SAY_MITZI_1 = -1568154 , SAY_MITZI_2 = -1568155 ,
SAY_MITZI_3 = -1568156 , SAY_MITZI_4 = -1568157 , SAY_CHRISTIAN_1 = -1568158 , SAY_CHRISTIAN_2 = -1568159 ,
SAY_CHRISTIAN_3 = -1568160 , SAY_CHRISTIAN_4 = -1568161 , SAY_BRENNAN_1 = -1568162 , SAY_BRENNAN_2 = -1568163 ,
SAY_BRENNAN_3 = -1568164 , SAY_BRENNAN_4 = -1568165 , SAY_HOLLEE_1 = -1568166 , SAY_HOLLEE_2 = -1568167 ,
SAY_HOLLEE_3 = -1568168 , SAY_HOLLEE_4 = -1568169 , SAY_MOJO = -1568170 , POINT_DESPAWN = 1 ,
SOUND_ID_FROG = 8353
}
enum {
SAY_START = -1568079 , SAY_AT_GONG = -1568080 , SAY_OPEN_ENTRANCE = -1568081 , SAY_OPEN_ENTRANCE_2 = -1568086 ,
SAY_SOUND_ALARM = -1568087 , GOSSIP_ITEM_ID_BEGIN = -3568000 , SPELL_BANGING_THE_GONG = 45225 , SPELL_SPEAR_THROW = 43647 ,
EQUIP_ID_HUGE_MAUL = 1012 , EQUIP_ID_GUARDIAN = 23597 , ENTRY_HARRISON_WITH_HAT = 24375
}
enum { SAY_GAUNTLET_START = -1568088 }
enum { SPELL_THUNDERCLAP = 44033 , SPELL_SUMMON_WARRIOR = 43486 , SPELL_SUMMON_EAGLE = 43487 }
enum {
GOSSIP_ITEM_ID_HARKOR_FREE = -3568001 , GOSSIP_ITEM_ID_HARKOR_DONE = -3568002 , GOSSIP_MENU_ID_HARKOR_DONE = 8917 , GOSSIP_MENU_ID_HARKOR_DONE2 = 8875 ,
SAY_HARKOR_HELP_1 = -1568089 , SAY_HARKOR_HELP_2 = -1568090 , SAY_HARKOR_HELP_3 = -1568091 , SAY_HARKOR_HELP_4 = -1568092 ,
SAY_HARKOR_EVENT_1 = -1568093 , SAY_HARKOR_EVENT_2 = -1568094 , SAY_HARKOR_EVENT_3 = -1568095 , EQUIP_ID_HARKOR = 23999 ,
SPELL_CRATE_BURST = 43255 , SOUND_ID_MONEY = 677 , SOUND_ID_CHEER = 2725 , SOUND_ID_APPLAUD = 6113
}
enum {
GOSSIP_ITEM_ID_TANZAR_FREE = -3568003 , GOSSIP_ITEM_ID_TANZAR_DONE = -3568004 , GOSSIP_ITEM_ID_TANZAR_DONE2 = -3568005 , GOSSIP_MENU_ID_TANZAR_DONE = 8916 ,
GOSSIP_MENU_ID_TANZAR_DONE2 = 8804 , GOSSIP_MENU_ID_TANZAR_DONE3 = 8807 , SAY_TANZAR_HELP_1 = -1568096 , SAY_TANZAR_HELP_2 = -1568097 ,
SAY_TANZAR_HELP_3 = -1568098 , SAY_TANZAR_HELP_4 = -1568099 , SAY_TANZAR_EVENT_1 = -1568100 , SAY_TANZAR_EVENT_2 = -1568101 ,
SAY_TANZAR_EVENT_3 = -1568102 , SAY_TANZAR_EVENT_3_ALT = -1568103 , SAY_TANZAR_EVENT_4 = -1568104 , SOUND_ID_APPLAUD_TANZAR = 6402 ,
SOUND_ID_CHEER_TANZAR = 6400 , SOUND_ID_EVENT_CELEBRATION = 12135 , EQUIP_ID_BONE_HAMMERS = 1117
}
enum {
GOSSIP_ITEM_ID_KRAZ_FREE = -3568006 , GOSSIP_ITEM_ID_KRAZ_DONE = -3568007 , NPC_TEXT_ID_KRAZ_DONE = 11602 , NPC_TEXT_ID_KRAZ_DONE2 = 11604 ,
SPELL_EXPLOSIVE_CHARGE = 43418 , SAY_KRAZ_HELP_1 = -1568105 , SAY_KRAZ_HELP_2 = -1568106 , SAY_KRAZ_HELP_3 = -1568107 ,
SAY_KRAZ_EVENT_1 = -1568108 , SAY_KRAZ_EVENT_2 = -1568109 , SAY_KRAZ_EVENT_3 = -1568110 , SAY_KRAZ_EVENT_4 = -1568111
}
enum {
GOSSIP_ITEM_ID_ASHLI_FREE = -3568008 , GOSSIP_ITEM_ID_ASHLI_DONE = -3568009 , GOSSIP_MENU_ID_ASHLI_DONE = 8876 , GOSSIP_MENU_ID_ASHLI_DONE2 = 8877 ,
SAY_ASHLI_HELP_1 = -1568112 , SAY_ASHLI_HELP_2 = -1568113 , SAY_ASHLI_HELP_3 = -1568114 , SAY_ASHLI_HELP_4 = -1568115 ,
SAY_ASHLI_EVENT_1 = -1568116 , SAY_ASHLI_EVENT_2 = -1568117 , SAY_ASHLI_EVENT_3 = -1568118 , SAY_ASHLI_EVENT_4 = -1568119 ,
SPELL_ASHLIS_FIREBALL = 43515 , SPELL_ASHLIS_FIREBALL_01 = 43520 , SPELL_ASHLIS_FIREBALL_02 = 43525 , SOUND_ID_EXCLAMATION = 6120 ,
SOUND_ID_APPLAUD_ASHLI = 2847 , SOUND_ID_APPLAUD_ASHLI2 = 6122
}
enum {
SPELL_ALERT_DRUMS = 42177 , SPELL_SHOOT = 16496 , SPELL_MULTI_SHOT = 43205 , SPELL_SUMMON_AMANISHI_SENTRIES = 42179 ,
SAY_ALARM = -1568120
}
enum { SPELL_CALL_OF_THE_BEAST = 43360 }
Functions
bool GossipHello_npc_harrison_jones_za (Player *player, Creature *creature)
bool GossipSelect_npc_harrison_jones_za (Player *player, Creature *creature, uint32, uint32 action)
bool ProcessEventId_event_ritual_of_power (uint32, Object *source, Object *, bool isStart)
bool GossipHello_npc_harkor (Player *player, Creature *creature)
bool GossipSelect_npc_harkor (Player *player, Creature *creature, uint32, uint32 action)
bool GossipHello_npc_tanzar (Player *player, Creature *creature)
bool GossipSelect_npc_tanzar (Player *player, Creature *creature, uint32, uint32 action)
bool GossipHello_npc_kraz (Player *player, Creature *creature)
bool GossipSelect_npc_kraz (Player *player, Creature *creature, uint32, uint32 action)
bool GossipHello_npc_ashli (Player *player, Creature *creature)
bool GossipSelect_npc_ashli (Player *player, Creature *creature, uint32, uint32 action)
bool GOUse_go_wooden_door (Player *player, GameObject *go)
void AddSC_zulaman ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_REMOVE_AMANI_CURSE
SPELL_PUSH_MOJO
SPELL_SUMMON_AMANI_CHARM_1
SPELL_SUMMON_AMANI_CHARM_2
SPELL_SUMMON_AMANI_CHARM_3
SPELL_SUMMON_AMANI_CHARM_4
SPELL_SUMMON_AMANI_CHARM_5
SPELL_SUMMON_MONEY_BAG
SPELL_STEALTH
NPC_FOREST_FROG
NPC_MANNUTH
NPC_DEEZ
NPC_GALATHRYN
NPC_ADARRAH
NPC_FUDGERICK
NPC_DARWEN
NPC_GUNTER
NPC_KYREN
NPC_MITZI
NPC_CHRISTIAN
NPC_BRENNAN
NPC_HOLLEE
SAY_MANNUTH_1
SAY_MANNUTH_2
SAY_MANNUTH_3
SAY_MANNUTH_4
SAY_DEEZ_1
SAY_DEEZ_2
SAY_DEEZ_3
SAY_DEEZ_4
SAY_GALATHRYN_1
SAY_GALATHRYN_2
SAY_GALATHRYN_3
SAY_GALATHRYN_4
SAY_ADARRAH_1
SAY_ADARRAH_2
SAY_ADARRAH_3
SAY_ADARRAH_4
SAY_DARWEN_1
SAY_DARWEN_2
SAY_DARWEN_3
SAY_DARWEN_4
SAY_FUDGERICK_1
SAY_FUDGERICK_2
SAY_FUDGERICK_3
SAY_FUDGERICK_4
SAY_GUNTER_1
SAY_GUNTER_2
SAY_GUNTER_3
SAY_GUNTER_4
SAY_KYREN_1
SAY_KYREN_2
SAY_KYREN_3
SAY_KYREN_4
SAY_MITZI_1
SAY_MITZI_2
SAY_MITZI_3
SAY_MITZI_4
SAY_CHRISTIAN_1
SAY_CHRISTIAN_2
SAY_CHRISTIAN_3
SAY_CHRISTIAN_4
SAY_BRENNAN_1
SAY_BRENNAN_2
SAY_BRENNAN_3
SAY_BRENNAN_4
SAY_HOLLEE_1
SAY_HOLLEE_2
SAY_HOLLEE_3
SAY_HOLLEE_4
SAY_MOJO
POINT_DESPAWN
SOUND_ID_FROG
Definition at line 45 of file zulamanScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_START
SAY_AT_GONG
SAY_OPEN_ENTRANCE
SAY_OPEN_ENTRANCE_2
SAY_SOUND_ALARM
GOSSIP_ITEM_ID_BEGIN
SPELL_BANGING_THE_GONG
SPELL_SPEAR_THROW
EQUIP_ID_HUGE_MAUL
EQUIP_ID_GUARDIAN
ENTRY_HARRISON_WITH_HAT
Definition at line 364 of file zulamanScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_GAUNTLET_START
Definition at line 564 of file zulamanScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_THUNDERCLAP
SPELL_SUMMON_WARRIOR
SPELL_SUMMON_EAGLE
Definition at line 627 of file zulamanScripts.cpp.
anonymous enum
anonymous enum
Enumerator
GOSSIP_ITEM_ID_HARKOR_FREE
GOSSIP_ITEM_ID_HARKOR_DONE
GOSSIP_MENU_ID_HARKOR_DONE
GOSSIP_MENU_ID_HARKOR_DONE2
SAY_HARKOR_HELP_1
SAY_HARKOR_HELP_2
SAY_HARKOR_HELP_3
SAY_HARKOR_HELP_4
SAY_HARKOR_EVENT_1
SAY_HARKOR_EVENT_2
SAY_HARKOR_EVENT_3
EQUIP_ID_HARKOR
SPELL_CRATE_BURST
SOUND_ID_MONEY
SOUND_ID_CHEER
SOUND_ID_APPLAUD
Definition at line 710 of file zulamanScripts.cpp.
anonymous enum
anonymous enum
Enumerator
GOSSIP_ITEM_ID_TANZAR_FREE
GOSSIP_ITEM_ID_TANZAR_DONE
GOSSIP_ITEM_ID_TANZAR_DONE2
GOSSIP_MENU_ID_TANZAR_DONE
GOSSIP_MENU_ID_TANZAR_DONE2
GOSSIP_MENU_ID_TANZAR_DONE3
SAY_TANZAR_HELP_1
SAY_TANZAR_HELP_2
SAY_TANZAR_HELP_3
SAY_TANZAR_HELP_4
SAY_TANZAR_EVENT_1
SAY_TANZAR_EVENT_2
SAY_TANZAR_EVENT_3
SAY_TANZAR_EVENT_3_ALT
SAY_TANZAR_EVENT_4
SOUND_ID_APPLAUD_TANZAR
SOUND_ID_CHEER_TANZAR
SOUND_ID_EVENT_CELEBRATION
EQUIP_ID_BONE_HAMMERS
Definition at line 1093 of file zulamanScripts.cpp.
anonymous enum
anonymous enum
Enumerator
GOSSIP_ITEM_ID_KRAZ_FREE
GOSSIP_ITEM_ID_KRAZ_DONE
NPC_TEXT_ID_KRAZ_DONE
NPC_TEXT_ID_KRAZ_DONE2
SPELL_EXPLOSIVE_CHARGE
SAY_KRAZ_HELP_1
SAY_KRAZ_HELP_2
SAY_KRAZ_HELP_3
SAY_KRAZ_EVENT_1
SAY_KRAZ_EVENT_2
SAY_KRAZ_EVENT_3
SAY_KRAZ_EVENT_4
Definition at line 1433 of file zulamanScripts.cpp.
anonymous enum
anonymous enum
Enumerator
GOSSIP_ITEM_ID_ASHLI_FREE
GOSSIP_ITEM_ID_ASHLI_DONE
GOSSIP_MENU_ID_ASHLI_DONE
GOSSIP_MENU_ID_ASHLI_DONE2
SAY_ASHLI_HELP_1
SAY_ASHLI_HELP_2
SAY_ASHLI_HELP_3
SAY_ASHLI_HELP_4
SAY_ASHLI_EVENT_1
SAY_ASHLI_EVENT_2
SAY_ASHLI_EVENT_3
SAY_ASHLI_EVENT_4
SPELL_ASHLIS_FIREBALL
SPELL_ASHLIS_FIREBALL_01
SPELL_ASHLIS_FIREBALL_02
SOUND_ID_EXCLAMATION
SOUND_ID_APPLAUD_ASHLI
SOUND_ID_APPLAUD_ASHLI2
Definition at line 1694 of file zulamanScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_ALERT_DRUMS
SPELL_SHOOT
SPELL_MULTI_SHOT
SPELL_SUMMON_AMANISHI_SENTRIES
SAY_ALARM
Definition at line 2057 of file zulamanScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_CALL_OF_THE_BEAST
Definition at line 2211 of file zulamanScripts.cpp.
Function Documentation
AddSC_zulaman()
void AddSC_zulaman ()
Definition at line 2267 of file zulamanScripts.cpp.
References Script::GetAI, GossipHello_npc_ashli(), GossipHello_npc_harkor(), GossipHello_npc_harrison_jones_za(), GossipHello_npc_kraz(), GossipHello_npc_tanzar(), GossipSelect_npc_ashli(), GossipSelect_npc_harkor(), GossipSelect_npc_harrison_jones_za(), GossipSelect_npc_kraz(), GossipSelect_npc_tanzar(), GOUse_go_wooden_door(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pGOUse, Script::pProcessEventId, ProcessEventId_event_ritual_of_power(), and Script::RegisterSelf().
Referenced by AddScripts().
GossipHello_npc_ashli()
bool GossipHello_npc_ashli (Player * player, Creature * creature)
Definition at line 2012 of file zulamanScripts.cpp.
References Creature::AI(), DONE, InstanceData::GetData(), Player::GetDefaultGossipMenuForSource(), WorldObject::GetInstanceData(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ID_ASHLI_DONE, GOSSIP_ITEM_ID_ASHLI_FREE, GOSSIP_MENU_ID_ASHLI_DONE, GOSSIP_SENDER_MAIN, Player::PrepareGossipMenu(), Player::SendPreparedGossip(), and TYPE_HALAZZI.
Referenced by AddSC_zulaman().
GossipHello_npc_harkor()
bool GossipHello_npc_harkor (Player * player, Creature * creature)
Definition at line 1049 of file zulamanScripts.cpp.
References Creature::AI(), DONE, InstanceData::GetData(), Player::GetDefaultGossipMenuForSource(), WorldObject::GetInstanceData(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ID_HARKOR_DONE, GOSSIP_ITEM_ID_HARKOR_FREE, GOSSIP_MENU_ID_HARKOR_DONE, GOSSIP_SENDER_MAIN, Player::PrepareGossipMenu(), Player::SendPreparedGossip(), and TYPE_AKILZON.
Referenced by AddSC_zulaman().
GossipHello_npc_harrison_jones_za()
bool GossipHello_npc_harrison_jones_za (Player * player, Creature * creature)
Definition at line 511 of file zulamanScripts.cpp.
References InstanceData::GetData(), Player::GetDefaultGossipMenuForSource(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ID_BEGIN, GOSSIP_SENDER_MAIN, Unit::isQuestGiver(), NOT_STARTED, Player::PrepareGossipMenu(), Player::PrepareQuestMenu(), Player::SendPreparedGossip(), and TYPE_EVENT_RUN.
Referenced by AddSC_zulaman().
GossipHello_npc_kraz()
bool GossipHello_npc_kraz (Player * player, Creature * creature)
Definition at line 1650 of file zulamanScripts.cpp.
References Creature::AI(), DONE, InstanceData::GetData(), Player::GetDefaultGossipMenuForSource(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ID_KRAZ_DONE, GOSSIP_ITEM_ID_KRAZ_FREE, GOSSIP_SENDER_MAIN, NPC_TEXT_ID_KRAZ_DONE, Player::PrepareGossipMenu(), Player::SendPreparedGossip(), and TYPE_JANALAI.
Referenced by AddSC_zulaman().
GossipHello_npc_tanzar()
bool GossipHello_npc_tanzar (Player * player, Creature * creature)
Definition at line 1383 of file zulamanScripts.cpp.
References Creature::AI(), DONE, InstanceData::GetData(), Player::GetDefaultGossipMenuForSource(), WorldObject::GetInstanceData(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ID_TANZAR_DONE, GOSSIP_ITEM_ID_TANZAR_FREE, GOSSIP_MENU_ID_TANZAR_DONE, GOSSIP_SENDER_MAIN, Player::PrepareGossipMenu(), Player::SendPreparedGossip(), and TYPE_NALORAKK.
Referenced by AddSC_zulaman().
GossipSelect_npc_ashli()
bool GossipSelect_npc_ashli (Player * player, Creature * creature, uint32 , uint32 action)
Definition at line 2034 of file zulamanScripts.cpp.
References Creature::AI(), GOSSIP_ACTION_INFO_DEF, GOSSIP_MENU_ID_ASHLI_DONE2, Player::PrepareGossipMenu(), and Player::SendPreparedGossip().
Referenced by AddSC_zulaman().
GossipSelect_npc_harkor()
bool GossipSelect_npc_harkor (Player * player, Creature * creature, uint32 , uint32 action)
Definition at line 1071 of file zulamanScripts.cpp.
References Creature::AI(), GOSSIP_ACTION_INFO_DEF, GOSSIP_MENU_ID_HARKOR_DONE2, Player::PrepareGossipMenu(), and Player::SendPreparedGossip().
Referenced by AddSC_zulaman().
GossipSelect_npc_harrison_jones_za()
bool GossipSelect_npc_harrison_jones_za (Player * player, Creature * creature, uint32 , uint32 action)
Definition at line 527 of file zulamanScripts.cpp.
References Creature::AI(), and GOSSIP_ACTION_INFO_DEF.
Referenced by AddSC_zulaman().
GossipSelect_npc_kraz()
bool GossipSelect_npc_kraz (Player * player, Creature * creature, uint32 , uint32 action)
Definition at line 1675 of file zulamanScripts.cpp.
References Creature::AI(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, and NPC_TEXT_ID_KRAZ_DONE2.
Referenced by AddSC_zulaman().
GossipSelect_npc_tanzar()
bool GossipSelect_npc_tanzar (Player * player, Creature * creature, uint32 , uint32 action)
Definition at line 1405 of file zulamanScripts.cpp.
References Creature::AI(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ID_TANZAR_DONE2, GOSSIP_MENU_ID_TANZAR_DONE2, GOSSIP_MENU_ID_TANZAR_DONE3, GOSSIP_SENDER_MAIN, Player::PrepareGossipMenu(), and Player::SendPreparedGossip().
Referenced by AddSC_zulaman().
GOUse_go_wooden_door()
bool GOUse_go_wooden_door (Player * player, GameObject * go)
Definition at line 2189 of file zulamanScripts.cpp.
References DONE, DoScriptText(), GetCreatureListWithEntryInGrid(), InstanceData::GetData(), WorldObject::GetInstanceData(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_SAVAGE, NPC_ZULJIN, SAY_INTRO, and TYPE_MALACRASS.
Referenced by AddSC_zulaman().
ProcessEventId_event_ritual_of_power()
bool ProcessEventId_event_ritual_of_power (uint32 , Object * source, Object * , bool isStart)
Definition at line 543 of file zulamanScripts.cpp.
References InstanceData::SetData(), SPECIAL, and TYPE_EVENT_RUN.
Referenced by AddSC_zulaman().