CMaNGOS_WoTLK: zuldrak.cpp File Reference
zuldrak.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "Entities/TemporarySpawn.h"
#include "Entities/Vehicle.h"
#include "AI/EventAI/CreatureEventAI.h"
Data Structures
struct npc_ghoul_feeding_bunnyAI
struct npc_decaying_ghoulAI
struct GymersBuddy
struct GymersThrow
struct SummonStefan
struct CharmGeist
struct HarvestBlightCrystal
struct TargetCrystal
struct CharmDrakuruServant
struct KillCreditDrakkariSkullcrusher
struct DrakuramasTeleportScript01
struct DrakuramasTeleportScript02
struct DrakuramasTeleportScript03
struct DropDisguise
struct ScourgeDisguiseExpiring
struct ArgentStandUnitRideGargoyle
struct CrusaderParachute
struct DeployParachute
struct ArgentStandUnit
struct HaveWitheredBatwing
struct HaveMuddyMireMaggot
struct HaveAmberseed
struct HaveChilledSerpentMucus
struct SummonCrusaderLeCraft
struct SummonCrusaderLamoof
struct SummonCrusaderJosephine
struct SummonPlagueSpray
struct ATangledSkeinEncasingWebsEffect
struct RandomIngredientAura
struct PotCheck
struct FetchAlchemistsApprentice
struct TossIceBoulder
struct Ghostly
struct RandomRadiusPicker
struct TailsUpSummonFemaleFrostLeopard
struct TailsUpSummonFemaleIcepawBear
Enumerations
enum { SPELL_ATTRACT_GHOUL = 52037 , SPELL_GHOUL_KILL_CREDIT = 52030 , NPC_DECAYING_GHOUL = 28565 }
enum { SPELL_BIRTH = 26047 , SPELL_FLESH_ROT = 28913 , NPC_GHOUL_FEEDING_BUNNY = 28591 }
enum { QUEST_DARK_HORIZON = 12664 , QUEST_REUNITED = 12663 , NPC_OVERLORD_DRAKURU = 28717 }
enum AlchemistsApprentice { QUEST_TROLL_PATROL_ALCHEMISTS_APPRENTICE = 12541 , SPELL_KILL_CREDIT_ALCHEMISTS_APPRENTICE = 51111 }
Functions
UnitAI * GetAI_npc_ghoul_feeding_bunny (Creature *pCreature)
UnitAI * GetAI_npc_decaying_ghoul (Creature *pCreature)
bool EffectDummyCreature_npc_decaying_ghoul (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
bool AreaTrigger_at_overlord_drakuru (Player *player, AreaTriggerEntry const *at)
void AddSC_zuldrak ()
Variables
std::vector< uint32 > easyAuras = { 51018, 51055, 51057, 51059, 51062, 51064, 51067, 51069, 51072, 51077, 51079 }
std::vector< uint32 > mediumAuras = { 51081, 51083, 51085, 51087, 51091 }
std::vector< uint32 > hardAuras = { 51093, 51095, 51097, 51100, 51102, 53150, 53153, 53158 }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_ATTRACT_GHOUL
SPELL_GHOUL_KILL_CREDIT
NPC_DECAYING_GHOUL
Definition at line 38 of file zuldrak.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_BIRTH
SPELL_FLESH_ROT
NPC_GHOUL_FEEDING_BUNNY
Definition at line 98 of file zuldrak.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_DARK_HORIZON
QUEST_REUNITED
NPC_OVERLORD_DRAKURU
Definition at line 236 of file zuldrak.cpp.
AlchemistsApprentice
enum AlchemistsApprentice
Enumerator
QUEST_TROLL_PATROL_ALCHEMISTS_APPRENTICE
SPELL_KILL_CREDIT_ALCHEMISTS_APPRENTICE
Definition at line 598 of file zuldrak.cpp.
Function Documentation
AddSC_zuldrak()
void AddSC_zuldrak ()
Definition at line 841 of file zuldrak.cpp.
References AreaTrigger_at_overlord_drakuru(), EffectDummyCreature_npc_decaying_ghoul(), Script::GetAI, GetAI_npc_decaying_ghoul(), GetAI_npc_ghoul_feeding_bunny(), Script::Name, Script::pAreaTrigger, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_overlord_drakuru()
bool AreaTrigger_at_overlord_drakuru (Player * player, AreaTriggerEntry const * at)
Definition at line 243 of file zuldrak.cpp.
References DoBroadcastText(), GetClosestCreatureWithEntry(), AreaTriggerEntry::id, Player::IsActiveQuest(), NPC_OVERLORD_DRAKURU, QUEST_DARK_HORIZON, and QUEST_REUNITED.
Referenced by AddSC_zuldrak().
EffectDummyCreature_npc_decaying_ghoul()
bool EffectDummyCreature_npc_decaying_ghoul (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 193 of file zuldrak.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, EFFECT_INDEX_0, Object::GetEntry(), NPC_DECAYING_GHOUL, NPC_GHOUL_FEEDING_BUNNY, UnitAI::SendAIEvent(), and SPELL_ATTRACT_GHOUL.
Referenced by AddSC_zuldrak().
GetAI_npc_decaying_ghoul()
UnitAI* GetAI_npc_decaying_ghoul (Creature * pCreature)
Definition at line 188 of file zuldrak.cpp.
Referenced by AddSC_zuldrak().
GetAI_npc_ghoul_feeding_bunny()
UnitAI* GetAI_npc_ghoul_feeding_bunny (Creature * pCreature)
Definition at line 89 of file zuldrak.cpp.
Referenced by AddSC_zuldrak().
Variable Documentation
easyAuras
std::vector<uint32> easyAuras = { 51018, 51055, 51057, 51059, 51062, 51064, 51067, 51069, 51072, 51077, 51079 }
Definition at line 594 of file zuldrak.cpp.
Referenced by PotCheck::OnEffectExecute(), and RandomIngredientAura::OnPeriodicDummy().
hardAuras
std::vector<uint32> hardAuras = { 51093, 51095, 51097, 51100, 51102, 53150, 53153, 53158 }
Definition at line 596 of file zuldrak.cpp.
Referenced by PotCheck::OnEffectExecute(), and RandomIngredientAura::OnPeriodicDummy().
mediumAuras
std::vector<uint32> mediumAuras = { 51081, 51083, 51085, 51087, 51091 }
Definition at line 595 of file zuldrak.cpp.
Referenced by PotCheck::OnEffectExecute(), and RandomIngredientAura::OnPeriodicDummy().