CMaNGOS_WoTLK: zulfarrak.cpp File Reference
zulfarrak.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "zulfarrak.h"
Functions
bool ProcessEventId_event_go_zulfarrak_gong (uint32, Object *pSource, Object *, bool bIsStart)
bool ProcessEventId_event_spell_unlocking (uint32, Object *pSource, Object *, bool bIsStart)
bool AreaTrigger_at_zulfarrak (Player *pPlayer, AreaTriggerEntry const *pAt)
void AddSC_zulfarrak ()
Function Documentation
AddSC_zulfarrak()
void AddSC_zulfarrak ()
Definition at line 105 of file zulfarrak.cpp.
References AreaTrigger_at_zulfarrak(), Script::Name, Script::pAreaTrigger, Script::pProcessEventId, ProcessEventId_event_go_zulfarrak_gong(), ProcessEventId_event_spell_unlocking(), and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_zulfarrak()
bool AreaTrigger_at_zulfarrak (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 80 of file zulfarrak.cpp.
References AREATRIGGER_ANTUSUL, FAIL, instance_zulfarrak::GetData(), WorldObject::GetInstanceData(), ScriptedInstance::GetSingleCreatureFromStorage(), AreaTriggerEntry::id, Unit::IsDead(), Player::IsGameMaster(), NOT_STARTED, NPC_ANTUSUL, and TYPE_ANTUSUL.
Referenced by AddSC_zulfarrak().
ProcessEventId_event_go_zulfarrak_gong()
bool ProcessEventId_event_go_zulfarrak_gong (uint32 , Object * pSource, Object * , bool bIsStart)
Definition at line 37 of file zulfarrak.cpp.
References FAIL, Object::GetTypeId(), IN_PROGRESS, NOT_STARTED, TYPE_GAHZRILLA, and TYPEID_PLAYER.
Referenced by AddSC_zulfarrak().
ProcessEventId_event_spell_unlocking()
bool ProcessEventId_event_spell_unlocking (uint32 , Object * pSource, Object * , bool bIsStart)
Definition at line 59 of file zulfarrak.cpp.
References Object::GetTypeId(), IN_PROGRESS, NOT_STARTED, TYPE_PYRAMID_EVENT, and TYPEID_PLAYER.
Referenced by AddSC_zulfarrak().