CMaNGOS_WoTLK: zulgurubScripts.cpp File Reference
zulgurubScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct npc_soulflayerAI
struct SummonNightmareIllusion
struct DelusionsOfJindo
struct SummonShadeOfJindo
struct RandomAggro
Enumerations
enum {
SPELL_SOUL_TAP = 24619 , SPELL_LIGHTNING_BREATH = 20543 , SPELL_THRASH = 12787 , SPELL_KNOCKDOWN = 20276 ,
SPELL_FEAR = 22678 , SPELL_FRENZY = 28371 , SPELL_ENRAGE = 8269
}
enum {
SPELL_CHAIN_BURN = 24684 , SPELL_SLEEP = 24664 , SPELL_EARTH_SHOCK = 24685 , SPELL_SUMMON_ILLUSION_1 = 24681 ,
SPELL_SUMMON_ILLUSION_2 = 24728 , SPELL_SUMMON_ILLUSION_3 = 24729
}
Functions
UnitAI * GetAI_npc_soulflayer (Creature *pCreature)
void AddSC_zulgurub ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_SOUL_TAP
SPELL_LIGHTNING_BREATH
SPELL_THRASH
SPELL_KNOCKDOWN
SPELL_FEAR
SPELL_FRENZY
SPELL_ENRAGE
Definition at line 29 of file zulgurubScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_CHAIN_BURN
SPELL_SLEEP
SPELL_EARTH_SHOCK
SPELL_SUMMON_ILLUSION_1
SPELL_SUMMON_ILLUSION_2
SPELL_SUMMON_ILLUSION_3
Definition at line 136 of file zulgurubScripts.cpp.
Function Documentation
AddSC_zulgurub()
void AddSC_zulgurub ()
Definition at line 190 of file zulgurubScripts.cpp.
References Script::GetAI, GetAI_npc_soulflayer(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_soulflayer()
UnitAI* GetAI_npc_soulflayer (Creature * pCreature)
Definition at line 131 of file zulgurubScripts.cpp.
Referenced by AddSC_zulgurub().